### ISSUE TITLE
Can start and end dates be replaced with academic years?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#10]
I have just noticed, that **there are no start/end dates** on the EUC IIA template. [We have included](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v0.2.0/endpoints/get-response.xsd#L151) them in the XSD, because we have them in the model. But do we actually need these dates?

Or, perhaps they should be optional?

Or, we should replace them with academic year references? (We already have those in `<cooperation-confiditions>` though, so this would be somewhat redundant.)

@erasmus-without-paper/all-members

**Comment by kaiqu** [comment]
> Or, we should replace them with academic year references? (We already have those in cooperation-confiditions though, so this would be somewhat redundant.)

I have no opinion on the dates on the IIA level, but the academic-year references in cooperation-conditions don't conform to the model (which has Start/End Date). Was it agreed at some point that it was enough with Academic Year in Cooperation Condition?

**Comment by wrygiel** [comment]
Start/end dates were quite vague, because you couldn't clearly tell how many students are being sent (or how many "iterations" there are). If I remember correctly, we have discussed it a long time ago on one of the meetings (I think Geir was there, so it must have been long time ago).

**Comment by kaiqu** [comment]
Ok, I assume there was a persuasive argument for this. I'll change the model to reflect it.

**Comment by wrygiel** [comment]
This argument mentioned above seemed very persuasive for me - this one:

> you couldn't clearly tell how many students are being sent (or how many "iterations" there are)

There's no such problem when academic years are listed.

**Comment by wrygiel** [comment]
Also have a look at this related issue - https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/12

**Comment by wrygiel** [comment]
(it's okay to replace these with academic year spans)

**Comment by wrygiel** [comment]
The comment above was a quick "note to self" posted directly during the meeting. Followup:

We have talked how this data is stored in various computer systems. Some implementations store it as a pair of academic terms, others store it as a pair of dates, others use a "starting academic term + duration"... In other words, there is no common way of doing this.

It has been suggested that there is no real use case for this data (it doesn't seem to be needed for any particular feature). It was noted that we already have a "signing date" for each of the partners, and that the scope of each agreement can be extracted from the cooperation conditions included.

We didn't have a clear conclusion if we should get rid of these fields, or replace them with academic year spans, but it probably doesn't matter what we do.

**Comment by kaiqu** [comment]
> It has been suggested that there is no real use case for this data (it doesn't seem to be needed for any particular feature). It was noted that we already have a "signing date" for each of the partners, and that the scope of each agreement can be extracted from the cooperation conditions included.

I would think it's useful to be able to verify that a Partner shares your understanding of the lifetime of the agreement, but you're right, it can be inferred from the Cooperation Conditions. If Academic Year is a fine enough granularity?

**Comment by wrygiel** [comment]
> I would think it's useful to be able to verify that a Partner shares your understanding of the lifetime of the agreement, but you're right, it can be inferred from the Cooperation Conditions.

Cooperation conditions also have academic-years only (at least in the format they do, and in some databases too). So no *specific* dates can be inferred from them (because the dates of academic years may slightly differ from partner to partner).

> If Academic Year is a fine enough granularity?

When I suggested this no one of the participants (there were about 8 of them at this time) had any objections. But I'm also quite sure they wouldn't object if we keep the dates, or remove them completely. Nobody could find any use case for keeping them, but they wouldn't mind providing them too (and in any format we choose).

This issue is somewhat related to https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/8 - if we switch to academic years here, then we will be able to use academic years for filtering in https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/8 (which seems a bit more explicit than using dates).

**Comment by kaiqu** [comment]
Then I'm fine with removing the dates from IIA.
