### ISSUE TITLE
When should IIA approval should be reset ?

### ISSUE THREAD

**Issue by anantqs** [erasmus-without-paper/ewp-specs-api-iias#103]
When do we reset IIA approval

- if the hash has been changed
- if the partner section is changed
- if any field in the api has been changed

**Comment by skishk** [comment]
> When do we reset IIA approval
> 
> * if the hash has been changed
> * if the partner section is changed
> * if any field in the api has been changed

Hello @anantqs,

is it a question with options or it is a affirmation from you ? 

i can say the first one for sure! when condition hash change :relaxed:

**Comment by anantqs** [comment]
what if the partner has changed their IIA ID and sent a new IIA ID ?

**Comment by skishk** [comment]
> what if the partner has changed their IIA ID and sent a new IIA ID ?

Partner can't change IIA ID :sweat_smile:

he can send new IIA ID that means it is a new Agreement

**Comment by spetronnetworks** [comment]
We know and experienced that there are partners/providers who changed their IIA ID.

**Comment by umesh-qs** [comment]
> > what if the partner has changed their IIA ID and sent a new IIA ID ?
> 
> Partner can't change IIA ID 😅
> 
> he can send new IIA ID that means it is a new Agreement

In the process of IIA negotiation, if a partner realizes that they have mapped wrong IIA and wants to correct it, why can't they change it?

**Comment by skishk** [comment]
> We know and experienced that there are partners/providers who changed their IIA ID.

yeah we experienced too this situation and it's not nice 😅

**Comment by skishk** [comment]
> > > what if the partner has changed their IIA ID and sent a new IIA ID ?
> > 
> > 
> > Partner can't change IIA ID 😅
> > he can send new IIA ID that means it is a new Agreement
> 
> In the process of IIA negotiation, if a partner realizes that they have mapped wrong IIA and wants to correct it, why can't they change it?

no one negotiate IIA ID 😅
ID for definition Identify something and it is used to unique identify something. if you change it that means you don't identify something in a unique way. new ID = new Agreement

**Comment by umesh-qs** [comment]
> > > > what if the partner has changed their IIA ID and sent a new IIA ID ?
> > > 
> > > 
> > > Partner can't change IIA ID 😅
> > > he can send new IIA ID that means it is a new Agreement
> > 
> > 
> > In the process of IIA negotiation, if a partner realizes that they have mapped wrong IIA and wants to correct it, why can't they change it?
> 
> no one negotiate IIA ID 😅 ID for definition Identify something and it is used to unique identify something. if you change it that means you don't identify something in a unique way. new ID = new Agreement

Yes new IIA is a new agreement in my system. I am changing the your linked IIA with my new internal IIA, because I mapped wrong IIA initially.

**Comment by skishk** [comment]
> Yes new IIA is a new agreement in my system. I am changing the your linked IIA with my new internal IIA, because I mapped wrong IIA initially.

oh yeah! that is great! and right! we can do the same because it is a possibile scenario. 

but here the question was about changing IIA ID not changing link between 2 IIA

**Comment by anantqs** [comment]
For more clarification

Step 1 : Partner A shared IIA with IIA-Id = 123 and shared it.
Step 2 : Partner B linked their IIA-Id = 456 with Partner A IID-ID=123 and shared it with condition hash as X
Step 3 : Partner A approves IIA. Send IIA Approval Cnr to Partner B.
Step 4 : Partner B receives the Approval from Partner A.
Step 5 : Partner B feels they wrongly linked wrong IIA-ID so they removes their linked IIA-Id = 456 and linked new IIA-Id=789 with Partner A IIA-Id=123 and shares it with condition hash as X 

Should partner A reset the approval even if the hash is still matching after step 5 done by partner B?

**Comment by skishk** [comment]
> Step 5 : Partner B feels they wrongly linked wrong IIA-ID so they removes their linked IIA-Id = 456 and linked new IIA-Id=789 with Partner A IIA-Id=123 and shares it with condition hash as X
> 
> Should partner A reset the approval even if the hash is still matching after step 5 done by partner B?

on step 5 , when partner B remove the link, have to send a IIA-CNR to partner A, so partner A see that there is a change in the link (no more link or now it's linked with something else, that means there is a change).
So Partner A received a change from Partner B so it's no more approved for him. so Partner a can send APPROVAL-CNR to say it's not approved or Partner B can check it on in the same way.

The important thing before sending something to partners is to check the actual version of IIA with a IIA-GET :smile:

**Comment by demilatof** [comment]
> Should partner A reset the approval even if the hash is still matching after step 5 done by partner B?

It's a different IIA, even if the condition hash is the same.
But if the hash code is the same, they have simply changed the IIA-ID. Why? 
These situations may happen, but they are so strange that I think that are due to B behavior, so A can implement the solution it likes better and B should accept it ;-) 
What could B do with the old IIA identical to the new one? It's useless.

**Comment by janinamincer-daszkiewicz** [comment]
This issue is discussed in https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/101.
