### ISSUE TITLE
Blended value

### ISSUE THREAD

**Issue by madiken21** [erasmus-without-paper/ewp-specs-api-iias#110]
It is specidied by W3C that xs:boolean can have these following litteral values: "true","false", "1", "0"
https://www.w3.org/TR/xmlschema-2/#boolean

So it is not possible to have the same hash if partner A use 'true/false' and partner B use '0/1' values

Shouldn't EWP specs limits authorized values to only true/false or 0/1 ?

**Comment by demilatof** [comment]
> So it is not possible to have the same hash if partner A use 'true/false' and partner B use '0/1' values

This doesn't matter; you get partner's IIA and you compute the hash code using its code, not yours.
And its computation must be the same of yours.
So, if it uses true/false in its XML, you check its hash code computing its XML with true/false.
If it use 0/1 you do the same, with 0/1
