### ISSUE TITLE
Use of IIA-CODE

### ISSUE THREAD

**Issue by skishk** [erasmus-without-paper/ewp-specs-api-iias#112]
In the Thessalonìki meeting I talked about the bad usage of IIA-CODE, so it is just to remember to all how we could use IIA-CODE because our IROs saw that some providers use it as an ID so it is not readable from the user.

you can find clarification here:
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/84cf84ce6c6322942cb697a95b1d64074d4dc863/endpoints/get-response.xsd#L117

so if the IIA-ID is for example : 84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863
IIA-CODE could not be the same of ID... must be something easy to read.

hope could be useful for the network

**Comment by umesh-qs** [comment]
I am aware that Dashboard is keeping same value for ID and Code. May be @kkaraogl  can explain or @janinamincer-daszkiewicz can throw some light if this is correct?

**Comment by kkaraogl** [comment]
How to better utilize the IIA-Code from remote partners is also a question of mine, for partners that do not use the same. 

For debugging reasons, for communication between technical teams, and for tickets in the SD, the IIA-ID is used. I can't recall of a case when a partner or a user came forward with just an IIA-CODE.

**Comment by skishk** [comment]
there are different scenarios of a wrong usage of IIA-ID and IIA-CODE:
scenario 1:

Partner A show IIA-ID (84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863) in the front-end, so IRO Partner A communicate something by email o call to the IRO of Partner B using what is seeing on his screen.
Partner B see on his screen the IIA-CODE (123456) so can't understand Partner A what is talking about...
(we must imagine this scenario for hundreds IIA)

Scenario 2:
Partner A use for his IIA-CODE the same value of IIA-ID (84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863) so it's something not human readable that create problems in communication by email or call.


in both scenarios IIA-CODE is not used well and that create problems between IROs.

it is really easy this specification so i hope all providers fix it with the correct usage of IIA-CODE.

**Comment by kkaraogl** [comment]
I do not see the problem in having the same, if they both are user-friendly.

This 84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863 in the IIA Code is definitely not user-friendly.

**Comment by skishk** [comment]
> 



> This 84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863 in the IIA Code is definitely not user-friendly.

yeah exactly if they are the same but readable it could be ok, but if they are like this, it's out of specification.

**Comment by kkaraogl** [comment]
Maybe adding examples in the specs, some dos and donts, so that everyone is on the same page. To be honest, it is already stated there that the IIA-CODE should be user-friendly already. 

@janinamincer-daszkiewicz what is your opinion on this?

**Comment by janinamincer-daszkiewicz** [comment]
I do not yet see what is missing in the current specs. If anybody of you see a problem in any part of specification concerning these codes - give your change proposal and we will together review it.

**Comment by skishk** [comment]
> give your change proposal and we will together review it.

probably just adding an example like:
CORRECT:
 IIA-ID = 84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863
 IIA-CODE = 123456

CORRECT:
 IIA-ID = 123456
 IIA-CODE = 123456
 
 WRONG:
 IIA-ID = 84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863
 IIA-CODE =  84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863

WRONG:
 IIA-ID = 123456
 IIA-CODE =  84cf84-ce6c6322-942cb697-a95b1d6-4074d4dc-863


and talking about this in the next IF forum could be helpful. 
I know that is a really simple specification... but believe me, I read emails threads between our IRO and partner IRO where no one is understanding something only for this wrong usage of the IIA-CODE.
I hope no one change IIA-ID if now is managing wrongly IIA-CODE.

**Comment by demilatof** [comment]
> probably just adding an example like:

Another useful tip maybe suggesting to modify the GUI to show "IIA ID" or "IIA Code" in front of the ID/Code, so that could be clear if the partner's IROs are referring to the IIA ID or to IIA Code

**Comment by janinamincer-daszkiewicz** [comment]
I wouldn't mind giving more examples in the specification but I am afraid that this will start a new discussion on what is user friendly and what is not. For me 123456 is OK, but 123456789 less OK. I would prefer something like IT-2023-001.

Could you share with me (by email) names of providers who use IIA-CODE which cannot be considered user-friendly by general standards? I will contact them. May be they just missed this part of the specification and will be willing to change their implementation?

I will also add slide to the presentation. We may not have time to discuss it but at least everybody will see.

**Comment by janinamincer-daszkiewicz** [comment]
Slides ready :)
