### ISSUE TITLE
Are the specifications compliant to the template?

### ISSUE THREAD

**Issue by demilatof** [erasmus-without-paper/ewp-specs-api-iias#114]
I understand that it could be a bit late, but I recently examined the last official templates [here](https://erasmus-plus.ec.europa.eu/resources-and-tools/inter-institutional-agreement) and now I'm not sure that the specifications are fully compliant with those templates.
Could you confirm me, and share with all of us, the decisions of DG EAC and BPO as concerns the specifications?
Or I have considered the wrong templates?

My doubts:

1. The specifications provide academic years at the mobility level; templates instead require academic year at agreement level. I understand that the specification proposes a more versatile solution, but I was sure that we had to stay with the template requirements
2. The specifications allow multiple area codes (Subject Areas) and multiple EQF levels per mobility whilst template requires ONE area code and ONE cycle per mobility

Why?
At a given point I thought that my HEI's IIAs weren't well formed, instead it seems to me that they are compliant with the official template, at least more than the specifications are.

**Comment by janinamincer-daszkiewicz** [comment]
Such decision has been made some time ago, but whatever was a reason for that now is time when Harpa and Paul and other colleagues review templates versus specifications and make decisions about alignement - either in one place or the other.
I ping @pleys - Paul, please take this issue into account in your current research.

**Comment by demilatof** [comment]
> Harpa and Paul and other colleagues review templates versus specifications and make decisions about alignement - either in one place or the other.

I thank you for the answer, maybe I wasn't yet involved in EWP developing, so I missed this point.
I'm quite scared by this possibility: "alignment - either in one place or the other".
What analysis could ever bring to specifications so different from the official template?
But, moreover, how can be possible that we are discussing about specification upgrade to 7.0, amendment by changing academic years in mobilities, for example, when in the meantime we have the possibility that it could be wrong relying on academic years per mobilities and not per agreements?
The same consideration is valid for EQF Levels and ISCED-F.
I spent time in adding the possibility to have more than one EQF Level and ISCED-F, but I have not yet populated the second and third level.
What should have to do IROs that already have made IIAs with more values per field?

**Comment by kamil-olszewski-uw** [comment]
> I'm quite scared by this possibility: "alignment - either in one place or the other".

This statement was about more things than those two. Maybe I shouldn't speak on behalf of my colleagues from DG EAC and EWP, but I can't imagine that these two things (after they were created as a result of joint internal debates and have been officially in operation for a long time) were changed in the specification to correspond to the current template.

**Comment by demilatof** [comment]
> This statement was about more things than those two. Maybe I shouldn't speak on behalf of my colleagues from DG EAC and EWP, but I can't imagine that these two things (after they were created as a result of joint internal debates and have been officially in operation for a long time) were changed in the specification to correspond to the current template.


I hope so, but in the meantime this means that the template cannot be a reference to clear eventually doubts.
We can discuss and adopt a solution, if we need, regardless what is written in the template.
