### ISSUE TITLE
how to manage a no solution from ESCI Service Desk and no answer to a direct email to Provider ?

### ISSUE THREAD

**Issue by skishk** [erasmus-without-paper/ewp-specs-api-iias#126]
we facing a issue with a partner that his response to our request IIA-INDEX-GET is a list of IIA-ID but then when we GET-IIA we receive a different IIA-ID in the response, and if we try to do a request on these different IIA-ID that we receive, we receive an empty response... 

Partner solicit our approval but he is ignoring that his provider generate some problem with the data.

any purpose to solve it? 

the problem is opened on ESCI service Desk in the beginning of May 2023...

**Comment by janinamincer-daszkiewicz** [comment]
@kamil-olszewski-uw  please take over.
What is the number in the ESCI SD?

**Comment by skishk** [comment]
> What is the number in the ESCI SD?

ESCI-6255

unfortunately this is only one of a list of no solved report...

**Comment by kamil-olszewski-uw** [comment]
I have access to the ESCI Service Desk from the support side and I know that my fellow supporters are doing a very good job handling many different tickets a day, the vast majority of which are successfully resolved.

Unfortunately, in situations like this, where none of the partners exchanging data via EWP use the Dashboard, my colleagues are dependent on the response of the partner provider.

My colleagues have not yet received a response to repeated contact requests. I have now written an email to my direct contact at your partner's provider. Hopefully we'll get an answer soon.

**Comment by skishk** [comment]
thank you ! 

the problem is: after more then 2 months we need a solution in few days now... the problem is in production not in DEV...

**Comment by georgschermann** [comment]
@skishk 
I looked into this with our team and those errors should be resolved most likely by tomorrow, at latest by the end of the week.
The reason for the missing answer was the size of the problem and missing permission/feedback by the HEI involved.
I will instruct my colleagues to send timely answers to the ESCI helpdesk, even if it is a no-solution-yet answer.
We will also check for additional similar issues and answer those.

**Comment by skishk** [comment]
please could you manage this tkt with a highest priority? --> ESCI-8593

there is a provider that use wrongly a HTTP 500 error to say no LA found 

thank you

**Comment by janinamincer-daszkiewicz** [comment]
@georgschermann, do you know this ticket? Do you want me to copy it here? Would you be so kind to comment? Is any more detailed explanation needed?

**Comment by janinamincer-daszkiewicz** [comment]
Ticket ESCI-8593 is resolved in SD.
