### ISSUE TITLE
Simplifying IIA response

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#13]
Currently, the IIA `get` response defines many elements "two times" - once for the local partner (e.g. [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/5ed29de47bbb762beef84d4781c63524043bc0b0/endpoints/get-response.xsd#L75)), and once for the remote partners (e.g. [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/5ed29de47bbb762beef84d4781c63524043bc0b0/endpoints/get-response.xsd#L186)).

Of course, these are often stored in separate entities in local databases, but perhaps making this separation on the representation level is somewhat confusing? Perhaps it would be easier to read the specification, if we simply had a `<partner>` element for the local partner too?

@erasmus-without-paper/all-members

**Comment by kaiqu** [comment]
A symmetrical representation would be more model-like. On the other hand, the format is inherently asymmetrical, since it represents the world as seen from the responding Partner. I have no strong opinions on this.

**Comment by wrygiel** [comment]
> On the other hand, the format is inherently asymmetrical, since it represents the world as seen from the responding Partner.

We may require that the first `<partner>` entry should always represent the the responding partner.

**Comment by kaiqu** [comment]
I leave it up to you.
