### ISSUE TITLE
The terminated-as-a-whole attribute should be part of the hashed string

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iias#135]
I am creating a new issue from my comment at https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/dd0f8a58c102a69b5b37484b545a2c5c994937d2#commitcomment-126261813 so that it is clearly visible to anyone subscribed to this repository.

_Why is the terminated-as-a-whole attribute not part of the hashed string? According to the voting results from 7 June 2023, termination as a whole should be treated like any other modification/termination, which, I suppose, implies that it should require a re-approval. Or am I missing something?_

Answer from @mkurzydlowski:
> You are right that it should be part of the hashed string to meet the requirements. The issue now is how to modify the XSLT without changing the major version of IIA.

Considering that providers have probably hardly started with the implementation, I would keep version 7.0.0 and make the necessary fixes regardless of them being backward incompatible. What else remains? To be a purist and increase the version to 8.0.0?

**Comment by demilatof** [comment]
> I am creating a new issue from my comment at [dd0f8a5#commitcomment-126261813](https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/dd0f8a58c102a69b5b37484b545a2c5c994937d2#commitcomment-126261813) so that it is clearly visible to anyone subscribed to this repository.
> 
> _Why is the terminated-as-a-whole attribute not part of the hashed string? According to the voting results from 7 June 2023, termination as a whole should be treated like any other modification/termination, which, I suppose, implies that it should require a re-approval. Or am I missing something?_

Simply because when I started coding the XLST, there was no official V7 to work on :wink: 


> > You are right that it should be part of the hashed string to meet the requirements. The issue now is how to modify the XSLT without changing the major version of IIA.
> 
> Considering that providers have probably hardly started with the implementation, I would keep version 7.0.0 and make the necessary fixes regardless of them being backward incompatible. What else remains? To be a purist and increase the version to 8.0.0?

We are testing v7 and XSLT, there is nothing in production. 
No one should consider the XSLT as the final version until explicitly stated.
It's enough to replace it and compute again the hash code, if someone has already did it.

I posted the possible solution here: https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/134#issuecomment-1713024742

**Comment by janinamincer-daszkiewicz** [comment]
https://github.com/erasmus-without-paper/ewp-specs-api-iias/compare/xslt-fix
