### ISSUE TITLE
Is IIA v6.3.0 backward compatible? Can it work together with v7? 

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-iias#138]
Please help me understand if as per the rules permanent DELETE can be added in a minor version when it is not backward compatible?
I saw it is optional to use IIA v6.3.0, so why is it even there? Can a provider on v6.3.0 do there test on v7.0 and get approval to host v7 in production registry?

**Comment by janinamincer-daszkiewicz** [comment]
> Please help me understand if as per the rules permanent DELETE can be added in a minor version when it is not backward compatible?

Umesh, I do not think this is worth our time to discuss if it is or not backward compatible. It has been issued in 6.3.0 which means that it can be tested in 6.3.0. It can also be tested in 7.0.0.

> I saw it is optional to use IIA v6.3.0, so why is it even there? 
To give the opportunity to those who have DELETE implemented to test before they are ready with all other stuff from 7.0.0.

> Can a provider on v6.3.0 do there test on v7.0 and get approval to host v7 in production registry?
I am not sure I understand you question so I will answer that way.
If you do not want to test DELETE as 6.3.0 you don't have to post 6.3.0. You can only post 7.0.0 and test it under 7.0.0. This will only mean that you will have to wait longer for partner ready to test 7.0.0.

Those who have DELETE under 6.3.0 cannot test it with those who have it under 7.0.0.

**Comment by umesh-qs** [comment]
> > Please help me understand if as per the rules permanent DELETE can be added in a minor version when it is not backward compatible?
> 
> Umesh, I do not think this is worth our time to discuss if it is or not backward compatible. It has been issued in 6.3.0 which means that it can be tested in 6.3.0. It can also be tested in 7.0.0.
> 
> > I saw it is optional to use IIA v6.3.0, so why is it even there?
> > To give the opportunity to those who have DELETE implemented to test before they are ready with all other stuff from 7.0.0.
> 
> > Can a provider on v6.3.0 do there test on v7.0 and get approval to host v7 in production registry?
> > I am not sure I understand you question so I will answer that way.
> > If you do not want to test DELETE as 6.3.0 you don't have to post 6.3.0. You can only post 7.0.0 and test it under 7.0.0. This will only mean that you will have to wait longer for partner ready to test 7.0.0.
> 
> Those who have DELETE under 6.3.0 cannot test it with those who have it under 7.0.0.

Janina, let me remind you the rules of API versioning. If its not worth your time, then may be DG EAC can respond. No one is forcing you. This is not a discussion. It is a question, as you (DG EAC) are in violation of the specification. And this violation has not been voted as acceptable. You (DG EAC) have introduced v6.3, on your own assumptions.
![image](https://github.com/erasmus-without-paper/ewp-specs-api-iias/assets/53461949/0a7a2ac0-351a-4038-a4f6-f7747fda3090)

Interesting to see that v6.3 and v7.0 cannot be tested together and at the same time v6.3 is optional. So you want to create a chaotic situation where some can choose v6.3 and some can v7.0 and then some who tested on 6.3 will test again on v7.0. And someone who are ready with v7.0 will have to wait.
What is the cut off for someone to finish v6.3 and then available to test on v7.0? This will create issues in meeting timeslines.

Finally ,what a great idea of having v6.3 that is not worth, but just because it is coming from the same "jury judge and executioner", it has to be discussed.

**Comment by janinamincer-daszkiewicz** [comment]
>Interesting to see that v6.3 and v7.0 cannot be tested together and at the same time v6.3 is optional. 

They can be tested at the same time. Such testing took part yesterday.
It's up to you and your partners to decide which order of testing you choose.

**Comment by umesh-qs** [comment]
> Those who have DELETE under 6.3.0 cannot test it with those who have it under 7.0.0.

Can you please explain then what is meant by "Those who have DELETE under 6.3.0 cannot test it with those who have it under 7.0.0.? Does it mean only partial testing can be done between v6.3 and v7.0?

**Comment by janinamincer-daszkiewicz** [comment]
Test are most effective if both partners test APIs in the same version.

**Comment by umesh-qs** [comment]
> Test are most effective if both partners test APIs in the same version.

Yes. So most effective it that there is no v6.3 and everyone tests on v7.0. You are a master at contradicting yourself and beating around the bushes. 
Asking again, why do we need v6.3 when the criteria for going live is v7.0?

**Comment by janinamincer-daszkiewicz** [comment]
> Yes. So most effective it that there is no v6.3 and everyone tests on v7.0.

Not true. During the workshop we have had testing sessions among 6.3.0 installations.

**Comment by umesh-qs** [comment]
> > Yes. So most effective it that there is no v6.3 and everyone tests on v7.0.
> > Not true. During the workshop we have had testing sessions among 6.3.0 installations.

You not true is only your interpretation. You are not coming to the point as always. We are working on a EWP network where specifications must be full proof. No scope of any if, but, may be, partner trust etc.  
Again, why do we have to test on 6.3 when criteria for live is 7.0? What is the timeframe for the providers to complete testing on 6.3 first before starting testing on 7.0?
Also v6.3 is against the rules of backward compatibility. You and DG EAC have chosen to bend the rules without taking explicit approval from other providers.
Please stop listening to Dashboard when designing/recommending specs. Some actions of DG EAC might at some point force providers to take a legal route. I am sure DG EAC would not want such a situation to arise.

Also, my colleague mentioned that in the recently concluded workshop, you named me as someone asking for permanent DELETE. If that is so, then you are absolutely wrong. In-fact we at QS were the only ones to vote against DELETE. You (triggered by Dashboard and approval from DG EAC) insisted on permanent DELETE. There isn't anything called temporary DELETE. In-fact if it is not permanent DELETE, then there is no change needed in specification. Providers can easily handle it in current specification.

**Comment by janinamincer-daszkiewicz** [comment]
> why do we have to test on 6.3 when criteria for live is 7.0? What is the timeframe for the providers to complete testing on 6.3 first before starting testing on 7.0?

You don't have to, you can. You can start with 7.0.0 whenever you wish.
