### ISSUE TITLE
Termination as whole scenario

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iias#149]
Concerning the 2023-11-30-TerminatedAsWhole.xlsx scenario published at https://esci-sd.atlassian.net/wiki/spaces/ITSC/pages/113999873/Infrastructure+Forum+and+technical+workshops I am quite surprised that it does not include approvals of the latest iia-hashes (A0.hash1 and B0.hash1). 

Where have we discussed and decided that the approvals of termination would be done in this way (i.e. just adding terminated-as-a-whole to the other IIA)? Can you point me to the discussion?

**Comment by janinamincer-daszkiewicz** [comment]
Why do you think that approvals are necessary in that case?
Isn't that unilateral decision of partner A?
Please write your proposal for the scenario, add it to this file in the next tab, it will be easier to discuss.

**Comment by jiripetrzelka** [comment]
I have not said that I think that approvals are necessary. It is irrelevant at this point what I think.
I said that I was surprised that your proposal is not in line with what I thought was agreed on. 

Now, I have found it myself:
https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/99#issuecomment-1537175707 
Last paragraph: _Note: Termination as a whole as any termination needs re-approval._

This sentence is also in the voting results on page 47 in 2023-05-17-InfrastructureForum.pdf:
<img width="947" alt="image" src="https://github.com/erasmus-without-paper/ewp-specs-api-iias/assets/1330161/7e3a44c6-3175-45f6-bd7f-c8146a49ec83">

I am sorry but it is not exactly my hobby to write these workflows...

**Comment by janinamincer-daszkiewicz** [comment]
My bad. Thank you for spotting. I will prepare the revised scenario and add the missing re-approval.

**Comment by janinamincer-daszkiewicz** [comment]
Please, review the new version, with approvals. It is named 2023-12-01-TerminatedAsWhole.xlsx.

**Comment by jiripetrzelka** [comment]
I think the scenario is ok now.

I am just adding one link regarding the grammar for reverting. I probably made the mistake myself many times so this is just to bring it to the attention of the community: https://www.vocabulary.com/dictionary/revert

**Comment by janinamincer-daszkiewicz** [comment]
Thank you,  I removed a couple of 'back'-s from 2023-10-28-DeleteModifyScenarios.xslx.
