### ISSUE TITLE
Stats when modifying mutually approved IIAs

### ISSUE THREAD

**Issue by JoelBlC** [erasmus-without-paper/ewp-specs-api-iias#154]
IIAs that are mutually approved and are being modified, should be considered as "iia-both-approved" or "iia-fetchable"?

In our opinion, it should be considered as "iia-both-approved" because it has already been approved, and we are just doing small changes to the agreement. 

We should also consider that it's a new approval and at some point it will be approved by one partner and not by the other ("iia-local-approved-partner-unapproved" or "iia-local-unapproved-partner-approve").

**Comment by janinamincer-daszkiewicz** [comment]
Very good question. We designed stats endpoints long before we started talking about modifying mutually approved IIAs. Also we don't want to extend the set of the statistics.
I have to think a while and consult the issue with the colleagues.

**Comment by janinamincer-daszkiewicz** [comment]
I think that from the business perspective the most important feature of such IIA is that it has been **mutually approved** and it will stay that way whatever happens in the future. Partners may start negotiations, but they will either revert or conclude so eventually this IIA will again be in the stable mutually approved state.
Which means that we should report such IIA as both, feachable and mutually approved.
Or saying in another way: for such IIA you should add 1 to the iia-fetchable counter and add 1 to the iia-both-approved counter .
Does it make sense?
P.S.
Sets of iia-local-unapproved-partner-approved, iia-local-approved-partner-unapproved and iia-both-approved should be disjoint.
Sets iia-local-unapproved-partner-approved, iia-local-approved-partner-unapproved and iia-both-approved should be subsets of iia-fetchable.

**Comment by demilatof** [comment]
Therefore, we could say that "iia-fetchable" is the number of IIA IDs we provide with Index API?
And "iia-both-approved" could be read as: we have XX IIAs "iia-fetchable", of which YY are "iia-both-approved"? (with XX>=YY)

**Comment by janinamincer-daszkiewicz** [comment]
> Therefore, we could say that "iia-fetchable" is the number of IIA IDs we provide with Index API? 
> And "iia-both-approved" could be read as: we have XX IIAs "iia-fetchable", of which YY are "iia-both-approved"? (with XX>=YY)

Yes
