### ISSUE TITLE
Clarifying `valid-for-approval` XSLT output element

### ISSUE THREAD

**Issue by mkurzydlowski** [erasmus-without-paper/ewp-specs-api-iias#156]
Answering an issue that was brought up during the last Infrastructure Forum meeting, I have created a [change proposal ](https://github.com/erasmus-without-paper/ewp-specs-api-iias/pull/155) to clarify `valid-for-approval` element that is part of the XSLT output. Please review it.

**Comment by janinamincer-daszkiewicz** [comment]
We were wondering locally in the team whether it is worth keeping the <valid-for-approval> attribute or getting rid of it. The prevailing opinion was that it does not cause any additional burden for programmers (it is generated by XSLT), and that it carries some additional information that the programmer **may** or **may not** use in the local implementation.

XSLT generates the result without knowing whether IIA is mutually approved. The presence of the <valid-for-approval> attribute means that IIA misses some values which are required in IIA v7 and should be accepted by a user. It could be used, for example, in the interface to alert end users.

All in all we decided to keep the <valid-for-approval> attribute but to better explain its role. See the proposal by Michał. 

Answering the question raised by Luis during the last meeting - after you generate <iia> with XSLT-v7 and you get <valid-for-approval> you can:
- ignore it,
- use it to additionally inform the users about the status of this IIA (you may even consider storing this information in a local table although we know that it is redundant).

**Comment by mkurzydlowski** [comment]
Change proposal (#155) has been merged.
