### ISSUE TITLE
XSLT produces invalid XML when the IIA-Get-Response contains more IIAs

### ISSUE THREAD

**Issue by demilatof** [erasmus-without-paper/ewp-specs-api-iias#159]
Thanks to @fioravanti-unibo 's notice, I have realized that there is a bug in the XSLTs, so that they produce invalid XML when the IIA-Get-Response contains more IIAs.
The problem is that if we have more than one IIA the XSLT output lacks the root element.
You can verify by yourself here https://www.w3schools.com/xml/xml_validator.asp
If you put in the validator box the actual result of XSLT transformation:

```
<?xml version="1.0" encoding="UTF-8"?>
<iia>
   <iia-id>iia_id_1</iia-id>
   <text-to-hash>this is the text to hash for the first IIA</text-to-hash>
</iia>
```
you have no error; **BUT** if you add a second IIA to the XML produced by the XSLT 

```
<?xml version="1.0" encoding="UTF-8"?>
<iia>
   <iia-id>iia_id_1</iia-id>
   <text-to-hash>this is the text to hash for the first IIA</text-to-hash>
</iia>
<iia>
   <iia-id>iia_id_2</iia-id>
   <text-to-hash>this is the text to hash for the second IIA</text-to-hash>
</iia>
```

The validation fails.
The solution is easy, just adding a wrapping element, e.g. <iia-processed>:

```
<?xml version="1.0" encoding="UTF-8"?>
<iia-processed>
   <iia>
      <iia-id>iia_id_1</iia-id>
      <text-to-hash>this is the text to hash for the first IIA</text-to-hash>
   </iia>
   <iia>
      <iia-id>iia_id_2</iia-id>
      <text-to-hash>this is the text to hash for the second IIA</text-to-hash>
   </iia>
</iia-processed>
```
The above code is correct for the W3C validator.

We can obtain a good XML just changing two lines in the XSLT.
For the [transform_version_7.xsl](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/resources/xsltKit/transform_version_7.xsl) we can

- add `<iia-processed>` at line 61
- add `</iia-processed>` after line 115

And similar for transform_version_6.xsl

**Comment by mkurzydlowski** [comment]
Is that a problem that makes it impossible to parse the XSLT output or does it only occur when you try to validate the output?

**Comment by fioravanti-unibo** [comment]
> Is that a problem that makes it impossible to parse the XSLT output or does it only occur when you try to validate the output?

To parse the document you have to pre-parse it with your preferred XML framework and this step fails: the document produced when there are multiple agreements is not _well formed_ because it is missing a root element, so **any** parser will fail.

There is no XML schema, so technically you can't and shouldn't validate it.

**Comment by mkurzydlowski** [comment]
Please review the [proposed change](https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/4a472fc587a0e9d32858f196130a9afa610d9ac5).

**Comment by demilatof** [comment]
> Please review the [proposed change](https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/4a472fc587a0e9d32858f196130a9afa610d9ac5).

It seems to me that now the two XSLTs produce good XML (I've tested them online).
Thanks
