### ISSUE TITLE
Months/weeks/days/hours in IIAs

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#16]
When it comes to expressing timespans, currently, IIA sections in XSD are compatible with the EUC IIA PDF template. In particular, `<staff-teacher-mobility-spec>` contains the `<avg-days>` element, which was meant to express the "average duration" mentioned here in the PDF:

![image](https://cloud.githubusercontent.com/assets/2168535/24545888/5eede9ee-1609-11e7-959d-65fb7664e6e1.png)

However, I am not really sure if the EUC IIA template really conforms to the "real-life practices". For example, our IRO claims that these should be expressed in hours, or in weeks, and that "8 hours" are equivalent to "1 week". Honestly, I don't understand much of it. Do we have an expert who could explain this model?

I would rather NOT include `<staff-teacher-mobility-spec>` in the specification, than include it with a wrong model.

@erasmus-without-paper/all-members

**Comment by vickalaser** [comment]
Hi,

This is the response from my Erasmus Co-ordinator.

Anthony

-----------------------------------
Days

The funding is calculated on the basis of days (as for students is done on Months (or pro rata by days).

Staff teaching need to:

·         do 8hrs of teaching in a work week, or part thereof
·         be a minimum of 2 days and maximum of 6 weeks

and they can include up to 2 days funded for travel – one before, one at end.

So we have always looked at staff mobility in terms of days for staff.
-------------------------------------

**Comment by wrygiel** [comment]
> Days
> 
> The funding is calculated on the basis of days (as for students is done on Months (or pro rata by days).
> 
> Staff teaching need to:
> 
> ·         do 8hrs of teaching in a work week, or part thereof
> ·         be a minimum of 2 days and maximum of 6 weeks
> 
> and they can include up to 2 days funded for travel – one before, one at end.
> 
> So we have always looked at staff mobility in terms of days for staff.

Thank you. I forwarded this to our IRO. As far as I know, they struggled with each other for some time, but they agreed that "days" is the way to go. :) I think we can close the issue.
