### ISSUE TITLE
Get-response xml Validation fails when "terminated-as-a-whole" element is set as true in xml 

### ISSUE THREAD

**Issue by anant6767** [erasmus-without-paper/ewp-specs-api-iias#161]
If 'terminated-as-a-whole' element is set as true in xml 
```xslt
      <ia7:cooperation-conditions>
	<ia7:terminated-as-a-whole>true</ia7:terminated-as-a-whole>
	<ia7:student-studies-mobility-spec>
		<ia7:sending-hei-id>moaea-bo.dev.com</ia7:sending-hei-id>
		<ia7:receiving-hei-id>moaes-bo.dev.com</ia7:receiving-hei-id>
		<ia7:receiving-first-academic-year-id>2024/2025</ia7:receiving-first-academic-year-id>
		<ia7:receiving-last-academic-year-id>2025/2026</ia7:receiving-last-academic-year-id>
		<ia7:mobilities-per-year>1</ia7:mobilities-per-year>
		<ia7:recommended-language-skill>
			<ia7:language>sq</ia7:language>
			<ia7:cefr-level>A2</ia7:cefr-level>
			<ia7:subject-area>
				<ia7:isced-f-code>9999</ia7:isced-f-code>
				<ia7:isced-clarification>Some clarification</ia7:isced-clarification>
			</ia7:subject-area>
		</ia7:recommended-language-skill>
		<ia7:other-info-terms>dddddasdasd</ia7:other-info-terms>
		<ia7:total-months-per-year>10</ia7:total-months-per-year>
		<ia7:blended>false</ia7:blended>
		<ia7:eqf-level>1</ia7:eqf-level>
		<ia7:eqf-level>2</ia7:eqf-level>
	</ia7:student-studies-mobility-spec>
   </ia7:cooperation-conditions>
``` 
and validated against the get-response.xsd(v7) schema.
Getting below error

"[\"Element '{https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/endpoints/get-response.xsd}
terminated-as-a-whole': This element is not expected. 
Expected is one of ( {https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/endpoints/get-response.xsd}student-studies-mobility-spec, 
{https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/endpoints/get-response.xsd}student-traineeship-mobility-spec,
{https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/endpoints/get-response.xsd}staff-teacher-mobility-spec, 
{https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/endpoints/get-response.xsd}staff-training-mobility-spec ).\"]"}

**Comment by mkurzydlowski** [comment]
`terminated-as-a-whole` is an attribute, not an element. So it should be:
`<ia7:cooperation-conditions terminated-as-a-whole="true">`

**Comment by anant6767** [comment]
oh my bad 
thanks
