### ISSUE TITLE
Hashes of the two IIA (one of each partner) will never match with XSLT?

### ISSUE THREAD

**Issue by lsanchezpe** [erasmus-without-paper/ewp-specs-api-iias#162]
Now the hash is calculated using the IIA_IDs, and considering that the fisrt ID displayed is different if the response is served by me or by my partner, I suppose that we can assume that the hash of my copy wil never match the hash of my partner's copy.

I mean, in older versions the hash betwen partners will only be different if something in the cooperation conditions was different. Wich in some cases dont mean that the content itself was different (for example I could use capital leters for the language codes and my partners don't).

Now whith the new calculation process even if i create an exact identical copy of my partners IIA, matching every single character, my hash and his hash wont match because of the order of the ids. 

I know this match was never been a must in order to approve an IIA, but I only want to be sure I understand the situation, because i was using this as a pre-comparission in order to detect identical IIAs in my system (for user interface purposse) and now i wont be able to do that.

**Comment by mkurzydlowski** [comment]
You are right but the old hash wasn't also suppose to match because every difference in the namespace, prefix, white space, etc. would make both copies of the IIA not to match.
