### ISSUE TITLE
Subject area at MobilityAdditional level or recommended-language-skill

### ISSUE THREAD

**Issue by lsanchezpe** [erasmus-without-paper/ewp-specs-api-iias#166]
I still don't completelly understand the difference between the subject-area specified inside the recommended-language-skill tag and the one inside the MobilityAdditional tag

Now that, for some kind of cooperation conditions the language skills is mandatory, and knowing that some of the providers doesn't allow to approve diferent iias its important to clarify this concepts.

Lets reduce to a simple scenario: i want to senda a cooperation condition in humanities and english C1.
What i should inform in my message?

1. One subject area at MobilityAdditional level and one language skill without any isced code in recommended-language-skill
2. None subject area at MobilityAdditional level but one language skill with the appropiate isced code recommended-language-skill
3. One subject area at MobilityAdditional  level and one language skill with the appropiate isced code recommended-language-skill

**Comment by janinamincer-daszkiewicz** [comment]
Luis,
I will try to explain how I understand it, basing my description on the contribution from Harpa and Kamil (in emails).

Your example is simple and the simple solution suffices.
In the first place you decide that the only acceptable ISCED code is humanities.
Then, in the language section you say that English C1 is expected for ALL ISCED codes (in that case there is only one - humanities). Which means that the first option on your list best fits this case: one cooperation condition with ISCED=humanities, and one language level English C1.

The second option 'hides' important information about ISCED codes in the language section - some systems order cooperating conditions by ISCED codes, they would have to gather them from a language section. Also in the mobility section each ISCED code is listed only once, in the language section it could show up more than once.

In the third option ISCED is redundant - if the same language is recommended for all ISCED codes there is no need to list them. Empty ISCED code means 'for all'.

Let's look at the more elaborate example. You accept students in humanities, mathematics and computer science (three ISCED codes). Recommended language skills are the following:

- French B2 for humanities
- English B2 for humanities
- English C1 for mathematics
- English C2 for computer science

Summary: 
1. List all ISCED codes in the mobility section.
2. List all language skills in the recommended-language-skill section and restrict them to particular ISCED codes, if needed.
