### ISSUE TITLE
How to handle this scenario ?

### ISSUE THREAD

**Issue by anant6767** [erasmus-without-paper/ewp-specs-api-iias#169]
Mutually approved > Change in Partner A > change approved in Partner B without making any changes in their copy

In Partner A, they show a message that both copies are not the same and it can't be approved
In Partner B, it shows as mutually approved

This is because Partner A requires IIAs to be exactly the same before approving. But Partner B allows for IIAs to not be exactly the same (generally, minor edits like ISCED clarifications or Additional Terms).
For the above scenario, the only option is for Partner B to also make a change and for Partner A to approve.
This was discussed in the workshop and clarified that IIAs need not exactly be the same. Logically, some data like mobility numbers or start\end academic years should not vary between the IIAs. However, that raises the question of what fields can be different. We request confirmation on the list of fields that need not be considered for approval.

**Comment by janinamincer-daszkiewicz** [comment]
I have added this issue to the agenda for the IF meeting on 20 March, 2024.

**Comment by demilatof** [comment]
> This is because Partner A requires IIAs to be exactly the same before approving. But Partner B allows for IIAs to not be exactly the same (generally, minor edits like ISCED clarifications or Additional Terms).

After this post https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/167#issuecomment-1974734367 I was quite sure that the term "equals" had been definitely abandoned for "equivalent"

**Comment by fioravanti-unibo** [comment]
the problem may be more serious than stated before.
If my copy of the IIA has the exact same data as my partner's but the data list is in a different order, the hashes are different.
If my partner wants to have the same hash, the IIA cannot be approved.

**Example:**

In my cooperation conditions I set out this list of language skills:

```
IT, with CEFR level B2
EN, with CEFR level A2
```

...while my partner, for the same condition exposes the list of language skills as 

```
EN, with CEFR level A2
IT, with CEFR level B2
```

The data are identical but the hash is different.

The same applies to the list of cooperation conditions: there is no defined mandatory order and the same data can be exposed in an almost infinite number of ways.

**Comment by janinamincer-daszkiewicz** [comment]
I close this issue because it is further discussed in https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/170.
