### ISSUE TITLE
avg-months as int value not fully expressive

### ISSUE THREAD

**Issue by georgschermann** [erasmus-without-paper/ewp-specs-api-iias#17]
E.g. we have a case with 3 mobilities and a total of 10 months.
When expressed as an avg-int you lose 1 month.

I'd suggest using the total-months, since the avg-months could be computed more precisely.

**Comment by wrygiel** [comment]
> we have a case with 3 mobilities and a total of 10 months.

Good point. I was wondering if this can happen, no I know.

How about adding `<xs:choice>` with both options? I know that `avg` can be inferred from `total`, but both formats seem to be very popular, and both are also allowed on the EUC PDF template.

**Comment by wrygiel** [comment]
I guess that `<total-days>` will also be needed?

**Comment by wrygiel** [comment]
Please review https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/18c0c860e350762c31671543e86624dd50d9fd10. Perhaps you will have a better suggestion for the annotations. At the moment, they sound a bit clunky.

**Comment by georgschermann** [comment]
we could stick to the iia template 

> total/average number of months of the study periods

don't know if this sounds better
