### ISSUE TITLE
How to calculate statistics for mutually approved IIAs which are under negotiations or terminated

### ISSUE THREAD

**Issue by janinamincer-daszkiewicz** [erasmus-without-paper/ewp-specs-api-iias#176]
During the last Infrastructure Forum (2024-05-15) one of the providers asked the following question:

_A question about statistics. How should mutually approved IIAs that have been modified be presented in the Stats response? Once approved by both do they always remain as such in the stats response or do the numbers need to change when modifications happen? Also if a mutually approved IIA is terminated, does it still appear in the stats response as approved by both or should it be removed?_ 

Currently in the stats endpoint we only recognize the following statuses of IIAs:

1. Fetchable – IIAs which are present in the index endpoint.
2. Approved by a partner but not approved locally.
3. Approved locally but not approved by a partner.
4. Mutually approved by both partners.

It means in particular that IIAs which have not yet been approved by anybody are only counted in Fetchable. We may also expect that at some point in time all fetchable will be either deleted or mutually approved. In an ideal EWP world, some day the number of fetchable should become equal to the number of mutually approved.

_index_ = _approvedByNone_ + _approvedLocally_ + _approvedByPartner_ + _approvedByBoth_

BPOs have not asked for more granular statistics on IIAs. Which means that we should choose the most suitable category from those which exist for mutually approved in the negotiation state and mutually approved which have been terminated.

Mutually approved by both which are in a negotiation state are still mutually approved by both. They may have active mobilities. Negotiations will eventually be finalized, one way or another. They seem to fit to _approvedByBoth_.

Terminated IIAs were once mutually approved which means that they will never dissapper from index. In that respect they are similar to _approvedByBoth_. They never had active mobilities. In that respect they are similar to _approvedByNone_. On the other hand the partners have made a decision about this IIA. They may change it some day and start negotiations (like for any other mutually approved IIAs) but it is not a pending state requiring action. All in all they seem to fit more to _approvedByBoth_.

With such interpretation the number of _approvedByBoth_ will never decrease which is also a nice feature.

Do you see any negative effects of such interpretation?

**Comment by umesh-qs** [comment]
I have not gone in detail yet .. is this interpretation different from what is currently in place? If so does it mean changes in the way current IIA stats are reported? What will be the timeline to implement this?

**Comment by janinamincer-daszkiewicz** [comment]
I cannot say how it is currently implemented by providers. Specification does not specifically address these particular two cases.

**Comment by umesh-qs** [comment]
So this is not a interpretation. This is in addition to what was there earlier. A new change for the providers.

**Comment by janinamincer-daszkiewicz** [comment]
Name it as you wish. I hope everybody implemented it as described as it is the most natural interpretation. The question has been asked so I answered.

**Comment by umesh-qs** [comment]
> Name it as you wish. I hope everybody implemented it as described as it is the most natural interpretation. The question has been asked so I answered.

So your work is done. Great. Why get into discussion and waste time. It is naturally there in the specification and no one has to make any changes.

**Comment by skishk** [comment]
> 4\. Mutually approved by both partners.

when they are both approved they will be always mutually approved, nothing to add or remove... the same is for terminated as a whole.

**Comment by demilatof** [comment]
> > 4. Mutually approved by both partners.
> 
> when they are both approved they will be always mutually approved, nothing to add or remove... the same is for terminated as a whole.

Exactly; I think that for stats we could consider the IIAs that are flagged as "in-effect", at least until we will keep on using that element.
Otherwise, we need a clear and strength definition of "mutually approved" in the specification, because currently the IIAs are "mutually approved" as soon as they become in-effect and they are again mutually approved as soon as a single IIA receive a new approval.

But this is not what BPOs want (page 8):
![bpo approved by both parties](https://github.com/erasmus-without-paper/ewp-specs-api-iias/assets/86968586/81c0b661-2d11-4220-896c-a5c333935b68)

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/resources/mandatory_business_requirements_IIA.pdf

And here again, another misuse of the "should" term: an agreement to be valid has to be approved by both partners?
YES => we need the term MUST
NO => we have to rewrite the concept

**Comment by janinamincer-daszkiewicz** [comment]
> YES => we need the term MUST

Mandatory Business Requirements are written in colloquial language.
