### ISSUE TITLE
Chicken and egg problem - matching IIAs among partners

### ISSUE THREAD

**Issue by mpuzar** [erasmus-without-paper/ewp-specs-api-iias#18]
I am implementing the IIA API now and wondering about what was the idea of an workflow that would get data into the database in the first place. It seems that both `partner/iia-id` and `partner/iia-code` are optional.

Let's say that Warszawa (UW) and Oslo (UIO) want to establish an IIA. My understanding is that, for now, this would be done outside of EWP? In that case, IIA_IDs on both sides are unknown and UW and UIO need to exchange their IIA_CODEs in order to be able to refer to the same IIA at a later point. However, if IIA_CODE is optional, how are they going to do that?

Let's assume that neither have a code. UIO can call UW's `/iias/index` to get a list of IIAs. It finds an IIA with IIA_ID='UWUIO1'. It then calls `/iias/get?iia_id=UWUIO1` - but there is no way to match that IIA with Oslo's local one without codes that BOTH sides know in advance.

Shouldn't both `partner/iia-id` and `partner/iia-code` be mandatory?

**Comment by wrygiel** [comment]
> Shouldn't both `partner/iia-id` and `partner/iia-code` be mandatory?

They already are, but only for the first partner. See [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/master/endpoints/get-response.xsd#L68).

**Comment by mpuzar** [comment]
Right (I was looking for a comment like that in the respective tags...)
Thanks.
