### ISSUE TITLE
Issues with iiaHashValidator on dev registry & ampersand

### ISSUE THREAD

**Issue by brankopetric** [erasmus-without-paper/ewp-specs-api-iias#180]
We have received IIA XML from partner with the wrong hash. 
https://dev-registry.erasmuswithoutpaper.eu/iiaHashValidator confirms it is correct.  
After examination of XML I conclude there is an issue with iiaHashValidator and &amp; character.

issue is with this line of XML file (isced-clarification is usually user input):
`<isced-clarification>ampersand &amp; char</isced-clarification>`

iiaHashValidator reports String used to calculate hash (text-to-hash):
`... ._student-studies-mobility-spec.subject-area.isced-clarification=ampersand & char_ ....  `
it change `&amp;` to & and then calculate hash. 
http://xsltransform.net/  and  https://linangdata.com/xslt-tester/    both confirm this text-to-hash is not correct

It would be nice if it could be fix at some point. Since we have to argue with partner which hash is correct :D

Minimal example for testing in attachment (XML not allowed TXT instead) 
[amper.txt](https://github.com/user-attachments/files/17247087/amper.txt)

Our calculation is: 0ecdd94b224853141b0ff241662e58aaeebcddfc4e44feb90109fcbf1e56fa58

**Comment by kkaraogl** [comment]
@brankopetric we also got an email from your address but it was detected as containing a virus from our mail server.

Please utilize the Service Desk to submit a ticket (https://esci-sd.atlassian.net/servicedesk/customer/portals), and the colleagues there will follow up, whether it concerns the EWP Dashboard or another provider. Thanks!

**Comment by mkurzydlowski** [comment]
> iiaHashValidator reports String used to calculate hash (text-to-hash): `... ._student-studies-mobility-spec.subject-area.isced-clarification=ampersand & char_ .... ` it change `&amp;` to & and then calculate hash.

That is true, but take note that & is the visible representation, but the XSLT used in the hash validator produces an XML with `&amp;`.

> http://xsltransform.net/ and https://linangdata.com/xslt-tester/ both confirm this text-to-hash is not correct

And it is the unescaped value that needs to be processed and hashed, not the raw escaped string used in the XML. The `&amp;` is only for escaping purposes:

https://www.w3.org/TR/xml/#syntax
> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively.

**Comment by brankopetric** [comment]
Thanks, Michał,

just to be clear, it may be useful to others also:

In text-to-hash we shoud use unescaped & and not raw (escaped) `&amp;` ?

And http://xsltransform.net/ and https://linangdata.com/xslt-tester/  should be ignored for testing in this case (or we shoul manually replace to unescaped value)?

**Comment by mkurzydlowski** [comment]
The XSLT works correctly and produces an XML that has to have an escaped & character.

But when reading an XML (like the one produced by the XSLT), you have to unescape the special XML characters like &.

So the hash is calculated on the unescaped value.

**Comment by brankopetric** [comment]
Thanks, closing
