### ISSUE TITLE
Start date and end date

### ISSUE THREAD

**Issue by mpuzar** [erasmus-without-paper/ewp-specs-api-iias#19]
It seems that neither `start_date` and `end_date` are defined as part of `get-response` (they should be at least inside `<partner/>` but possibly also `<iia/>` itself). Have I missed something?

**Comment by wrygiel** [comment]
They were there, but were removed later on. See [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/10).

**Comment by mpuzar** [comment]
Ah, sorry. I manage to overlook the existence of closed issues also (which are by default hidden).
