### ISSUE TITLE
Sending non-Erasmus IIAs via IIAs API?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#20]
Developers from Poland proposed making the [`mobilities-per-year` element](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/c9a2df4c57f0645ba4d8d1021fb491fa874b8b53/endpoints/get-response.xsd#L390) optional. They say this will not "hurt" Erasmus agreements, and it would allow IIAs API to be used to exchange information about *any* agreements (not only Erasmus ones).

@erasmus-without-paper/all-members - would any of you want to use such feature? Would you expose non-Erasmus IIAs?

Personally, I am confused. I'm afraid that these non-Erasmus agreements might have entirely different structure/model than the Erasmus ones. If so, then extending IIAs API in this direction seems a bad idea. I'm not an expert on the topic though.

* Are all these non-Erasmus agreements always related to mobilities?
* If so, then are all these mobilities limited to the same set of [4 types](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/c9a2df4c57f0645ba4d8d1021fb491fa874b8b53/endpoints/get-response.xsd#L212) which Erasmus agreements defines?
* Can all of them have optional "recommended-language-skill" and/or "isced-f-code"?
* Do we need to distinguish between Erasmus and non-Erasmus IIAs? Some kind of agreement-type?

**Comment by paulleys** [comment]
@wrygiel at Ghent University the structure/model of our non-Erasmus agreements is completely different from the Erasmus agreements.

**Comment by wrygiel** [comment]
Okay, our developers dropped the issue for now. Perhaps we will re-open it in EWP 2.0.
