### ISSUE TITLE
Ability to attach scanned PDFs to IIAs

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#21]
Something to think about. Perhaps in EWP 2.0?

It has been proposed that partners could optionally serve **scanned PDFs of actually signed IIAs**, via EWP. 

This would be easy to add, but I think we should wait with this until at least a couple of partners agree that they would serve and/or fetch it. We don't want to clutter our APIs with unused features.

**Comment by wrygiel** [comment]
@janinamincer-daszkiewicz, please correct me if I'm wrong.

Polish developers suggested (though, as usual, in private conversations), that these PDFs (either scanned or generated) would be useful for them. If I understood it correctly, for archiving.

They also suggested, that perhaps we might allow receiving HEIs to approve LAs based on such PDFs (instead of approving XML contents).

@erasmus-without-paper/all-members

**Comment by janinamincer-daszkiewicz** [comment]
Yes, I confirm. What the others think about sending PDFs?

**Comment by wrygiel** [comment]
Related question:

If we allow approving PDF LAs, then should we make it optional to support `<components-studied>` and `<components-recognized>` elements? If we did, then HEIs would be able to choose which way of LA approval they support - either the electronic way, or the PDF way, or both.

**Comment by wrygiel** [comment]
I just realized, that there are two separated topics mixed in this thread.

The original thread was about IIAs, but then I mistakenly merged it with a completely new topic related to LAs.

**Comment by wrygiel** [comment]
I will clean it up now. I will create a separate thread for the LA-related topic.

**Comment by wrygiel** [comment]
Related topic about PDFs in LAs (not IIAs): https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/issues/26

**Comment by georgschermann** [comment]
This came up again during our tests with Universities. One advantage would be, that there could be a common document for all partners and not every partner starts their own document. And obviously the simple exchange of "real" or electronic signatures.

**Comment by janinamincer-daszkiewicz** [comment]
From the Minutes from the Technical meeting in Malaga (2019-09-12).

> It has been proposed that partners could optionally serve scanned PDFs of actually signed IIAs, via EWP. Bavo suggested that PDFs could be signed in XML, gathering different signatures for the same document.  Nevertheless, the main question is: are PDFs needed?

> Joao believes the PDF can be an optional field. Victoriano agrees (it can include the note “a PDF may be attached to this document”). Gerald also agrees that an institution can use it as an option for comments.

> Stefan asked how heavy the PDFs are. Victoriano doesn’t think that would be an important issue, since we can add an URL instead and if anyone wants to see it, just click on it. All in the same API  (the Inter-Institutional Agreement). Georg agrees (either with the PDF itself or the URL, as far as it can be incorporated).

> Despite the ease of integration of this procedure, Stefan opposed encouraging the addition of PDFs. In his view, the EWP team should try to implement societal change and stop the introduction of PDFs in mobility processes; he doesn’t think that it should be part of the official API of the IIA and if needed should be in a new API. Janina believes it should be part of the API of the IIA and shouldn’t be in any other.

The meeting is stopped here because the room has to be vacated.

**Comment by georgschermann** [comment]
Embedding of an URL has been reconsidered, since the URL would have to be public, which is fine for institutional fact sheets, but most likely not for signed, legal documents. We could add the PDF as an optional field in the IIA get endpoint, which should only be filled, if the PDF contains data which is not present in the XML or specify an additional endpoint to retrieve the PDF.

**Comment by janinamincer-daszkiewicz** [comment]
PDFs are discussed in https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/30.

**Comment by BavoNootaert** [comment]
Why would the URL have to be public? We could specify that the request to that URL should also contain an HTTP Signature.

**Comment by georgschermann** [comment]
Urls would have to be public to (easily) use them in the frontend or save them anywhere. Using HTTP Signatures would be a possible solution and would be the same as using a (separate) API-endpoint for the PDFs since it could only be used by an EWP-host.

**Comment by janinamincer-daszkiewicz** [comment]
Done:
https://github.com/erasmus-without-paper/ewp-specs-api-iias, ver. 2.2.1 
https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/stable-v2/example-scenario , ver. 2.2.1
https://github.com/erasmus-without-paper/ewp-specs-api-iias-approval, ver. 0.1
https://github.com/erasmus-without-paper/ewp-specs-api-iia-approval-cnr, ver. 0.1
The last two will be made stable after the first reference implementation.
