### ISSUE TITLE
Release some stable versions + bump XML namespaces

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#22]
@erasmus-without-paper/all-members 

### 1.0.0 versions of IIAs API and IIA CNR API

I think it's time to release the stable versions of IIAs API and IIA CNR API. I can see that many partners have already implemented IIAs API, so I guess they have also cross-validated the specifications, and we may consider them stable. IIA CNR API hasn't been implemented, but I think we can make it stable too (because these two are much related).

### Bump all other XML namespaces to `stable-v1`?

Quote from the *Working with EWP Technical Documentation* document ([version 1.2.0](https://github.com/erasmus-without-paper/ewp-specs-management/tree/v1.2.0)). This was changed recently:

>    Unreleased (draft) APIs also SHOULD use valid GitHub URLs for theirs XML
>    namespaces. They MAY use URLs referring to the `master` branch, but they
>    also MAY use URLs referring to the - not yet existing - `stable-v1` branch
>    (for forward-compatibility). This DOES NOT mean that you can have draft
>    changes in `stable-v1` branch - it only means that you can use `stable-v1`
>    *XML namespace* in your `master` branch.

In fact, I now think it was a bad decision to have `master` XML namespaces in the beginning. We should have started with `stable-v1`, not `master`. Note, that this does not prevent us from introducing backward-incompatible things in `0.x.y` versions. It does however allow us to migrate from `0.x.y` version to `1.0.0` version without much of a hassle.

That said, I think it might be a good idea to perform this action now (changing `master` to `stable-v1` in all XML namespaces), without marking the APIs themselves as stable yet (they will still be `0.x.y`). This, of course, would break some implementations, so we should schedule some specific date for that action (we would ask all developers to switch to the new namespace on this date). When would be a good time for that?

**Comment by wrygiel** [comment]
> When would be a good time for that?

I propose 12th of June (2017-06-12). @erasmus-without-paper/all-members, will this be okay with you? I would push these changes to all repositories either on this day, or a couple of days before it.

**Comment by georgschermann** [comment]
ok for us

**Comment by mkurzydlowski** [comment]
OK :)

**Comment by wrygiel** [comment]
Quote from email we just sent.

> As we previously announced, today (or - at the latest - before the end of this week), we expect all EWP developers to change all XML namespaces in their implementations of draft APIs from `master` to `stable-v1`.
>
> * For most developers, this step should be easy - you just need to find all occurrences of `master` in your project and replace those with `stable-v1`.
>
> * If possible, then you should also bump API versions in your `manifest.xml` files.
>
> We have released new `0.x.y` versions of all draft APIs. Currently, none of them have `master` in their XML namespaces.
