### ISSUE TITLE
Cardinality of Cooperation Conditions

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-iias#3]
IIAs can be multilateral. Is that the case for Cooperation Conditions as well?
I.e. if there are 3 Partners in an IIA, can a Cooperation Condition be three-way?

**Comment by janinamincer-daszkiewicz** [comment]
I don't think so. In our database all CC have only two parties and we describe their incoming students/staff and our outgoing students/staff.

**Comment by wrygiel** [comment]
As far as I remember, each condition is always between two organization units.

**Comment by kaiqu** [comment]
Ok, thanks.
