### ISSUE TITLE
Additional Information / Comments 

### ISSUE THREAD

**Issue by georgschermann** [erasmus-without-paper/ewp-specs-api-iias#32]
During our tests with universities the following problem came up:
For some universities the ISCED code is not enough to specify the agreements.
They have their agreements on a study field level and multiple study fields per ISCED code which may not be related at all.  The Study fields of one ISCED code may be distributed among multiple faculties and different agreements for different study fields of the same ISCED code may be present. 
With the Agreements on ISCED level multiple identical IIAs would exists, IIAs could not be correctly matched to local Agreements and partners could not predict if an exchange for a specific study field of the ISCED code is possible.

For example two identical IIAs for ISCED code "0231 - Language acquisition" could exist.
One for German, one for English. Now 0231 covers about 30 Languages and exchange students won't be accepted for 28 of them. The study fields are also part of the official agreement documents of these Universities.

I'd propose some sort of additional information or comment field(s) on coop-conditions to further restrict / specify the coop-condition.

**Comment by janinamincer-daszkiewicz** [comment]
From the Minutes from the Technical meeting in Malaga (2019-09-12).

> Janina explained that we have the code in the official template (ISCED code). It has its official name. In the template, we have the field for the name connected to the code. However, we assumed it  would be the official name of the ISCED code. We need a field for the ISCED code, the ISCED name and an extra comment field. The extra will not be in the template. The XML will need only one extra field for the name, because if we send the ISCED code, every partner can read the name connected to the ISCED code and the extra text field is empty anyway. We don’t have to send the redundant information via the network. We either send the name of the ISCED code or the code, so the name-field can be reused. Gerald agreed that this field is enough.

Marta will update the specification.

**Comment by MartaJuzepczuk** [comment]
We plan to add one element to the IIAs get response:

```xml
<xs:element name="subject-area-name" type="xs:string" minOccurs="0" maxOccurs="1">`
    <xs:annotation>
        <xs:documentation>
            Subject area name associated with this mobility.

            It can be a name of the ISCED-F code sent in the `isced-f-code` element,
            but does not have to. In some cases it is useful to have more detailed
            information here.
        </xs:documentation>
    </xs:annotation>
</xs:element>
```

@georgschermann  Is it ok for you?
