### ISSUE TITLE
Adapt EWP APIs to the new agreement template

### ISSUE THREAD

**Issue by MartaJuzepczuk** [erasmus-without-paper/ewp-specs-api-iias#36]
We may need some changes in the IIAs API and maybe also in other EWP APIs according to the new template of the interinstitutional agreements.

The new template is available [here](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v2/resources/template_EuropeanCommission_IIA_21-29.pdf) and [here](https://ec.europa.eu/programmes/erasmus-plus/resources/documents/information-about-inter-instutional-agreements-between-programme-countries-calls_en).

**Comment by MartaJuzepczuk** [comment]
While preparing changes in the API we should remember that we will also use it to send old agreements and agreements that are in preparation (maybe having some information worth sharing, but not necessarily all the information required by the template).

**Comment by pleys** [comment]
The IIA API focuses on the terms of agreements from the official template.

Some elements to be taken into account when revising the current IIA APIs:
-	blended mobilities is missing
-	“Contact” & “signing contact” is optional in API, “contact” is required in IIAM 
-	the API allows total or average duration (something that was mentioned on the previous template) but the new template is clear about total number of months (for students) and days (for staff).

**Comment by fmapeixoto** [comment]
Hello,

I have checked and most of the fields we already have stay more or less the same.

The fields that Paul mentioned I think are the most relevant to add in the new version of the API:
- missing blended for student (true or false)
- in the IIAm we require the contact information and website
- and in student and staff mobility there are no average anymore

Now regarding the all the other information in the template, I wonder where it all comes from (maybe we can add some api to give this information so it would be always up to date, namely:
- we need to make sure that each hei exposes the erasmus code in the registry or somewhere because we need to match the hei_id and erasmus code
- the calendar dates information (autumn and spring for each of them)
- the visa/housing/insurance information (contacts and website)
- the additional requirements (requirement, details, contacts and website)
- the inclusion infrastructure and services (type of infrastructure/service, description, contacts and website)
- the additional information needs (type, contacts and website)
- the decision weeks
- the ToR number of weeks

**Comment by EvelienRenders** [comment]
@fmapeixoto I agree with your list. What do you mean by 'decision weeks'?

**Comment by fmapeixoto** [comment]
@EvelienRenders I was referring to the sentence in the new template that says "The institution will send its decision within [x] weeks, and no later than 5 weeks."

**Comment by janinamincer-daszkiewicz** [comment]
> While preparing changes in the API we should remember that we will also use it to send old agreements and agreements that are in preparation (maybe having some information worth sharing, but not necessarily all the information required by the template).

@pleys @fmapeixoto Could you comment on that?
We might still have some fields optional on the XML level but eventually mandatory on the business level. That would allow us to stay backward compatible and exchange draft versions. But of course on the business level we would expect all mandatory fields to be available before approving the agreement.

**Comment by MartaJuzepczuk** [comment]
> * missing blended for student (true or false)

I will add such field. Should it be added only to `student mobilities for studies` or to `student mobilities for traineeships` too? Should it be required? If so, what should be sent for old IIAs?

> * in the IIAm we require the contact information and website

What about old IIAs and IIAs in preparation? Maybe we should leave those elements optional, but write in the description, that it should be sent for new IIAs and that partner will not sign an agreement without this?

> * and in student and staff mobility there are no average anymore

I can remove average. There was an idea to replace it with the total even before the new template (https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/17).

> Now regarding the all the other information in the template, I wonder where it all comes from (maybe we can add some api to give this information so it would be always up to date, namely:
> 
> * we need to make sure that each hei exposes the erasmus code in the registry or somewhere because we need to match the hei_id and erasmus code

What do you mean by "make sure"?

> * the calendar dates information (autumn and spring for each of them)
> * the visa/housing/insurance information (contacts and website)
> * the additional requirements (requirement, details, contacts and website)
> * the inclusion infrastructure and services (type of infrastructure/service, description, contacts and website)
> * the additional information needs (type, contacts and website)
> * the decision weeks
> * the ToR number of weeks

Is PDF factsheet not sufficient? Should we add an API for the information in factsheet? Do clients need this information in structural form? Do heis keep such information in the database?

**Comment by fmapeixoto** [comment]
@janinamincer-daszkiewicz , @MartaJuzepczuk , I have no problem, in order to maintain backward compatibility, in keeping some fields as optional but we can only accept agreements, at a business level, if they are present (mandatory).

Regarding the blended mobility is for both student mobilities for studies and to student mobilities for traineeships.

By "make sure" I was thinking that each hei in the registry has the option to expose in the bottom the erasmus code, the eche code, the pic, etc, but they are not mandatory right? And we need to at least have the erasmus code to match the agreements with hei_id's. Do you understand?

I am following the template and the fields present there and for a lot of tables there is at least a contact, email and website information, which I believe can be different in each section. As this information can change from time to time, I was suggesting to make a new API only with this information so we can always have the info up to date in each agreement.

**Comment by janinamincer-daszkiewicz** [comment]
> By "make sure" I was thinking that each hei in the registry has the option to expose in the bottom the erasmus code, the eche code, the pic, etc, but they are not mandatory right? And we need to at least have the erasmus code to match the agreements with hei_id's. Do you understand?

I understand, but I don't know what change you suggest.

> contact, email and website information, which I believe can be different in each section.

Every agreement may have its own data. What change you suggest?

**Comment by fmapeixoto** [comment]
> > By "make sure" I was thinking that each hei in the registry has the option to expose in the bottom the erasmus code, the eche code, the pic, etc, but they are not mandatory right? And we need to at least have the erasmus code to match the agreements with hei_id's. Do you understand?
> 
> I understand, but I don't know what change you suggest.

To be honest, I don't know, open to discuss, but maybe adding just a text saying that Hei's that do not expose Erasmus Codes we will not be able to sign agreements with them.

> 
> > contact, email and website information, which I believe can be different in each section.
> 
> Every agreement may have its own data. What change you suggest?

I am not sure that this "Factsheet" data is unique per agreement, as for example a website with information, if the URL changed and the data is not related to the agreement but in a different API we can always have the data in the agreement up to date and correct. Do you see? Maybe a different API where you specify the agreement ID and gives you all the calendar and "factsheet" (contacts and websites) information, no?

**Comment by janinamincer-daszkiewicz** [comment]
> To be honest, I don't know, open to discuss, but maybe adding just a text saying that Hei's that do not expose Erasmus Codes we will not be able to sign agreements with them.

That would be OK for us. Very strong warning in the specification.
@pleys, @EvelienRenders  what do you think?
> 
> I am not sure that this "Factsheet" data is unique per agreement, as for example a website with information, if the URL changed and the data is not related to the agreement but in a different API we can always have the data in the agreement up to date and correct. Do you see? Maybe a different API where you specify the agreement ID and gives you all the calendar and "factsheet" (contacts and websites) information, no?

@MartaJuzepczuk, @pleys, @EvelienRenders, @georgschermann  what is your opinion?

**Comment by MartaJuzepczuk** [comment]
> I am not sure that this "Factsheet" data is unique per agreement, as for example a website with information, if the URL changed and the data is not related to the agreement but in a different API we can always have the data in the agreement up to date and correct. Do you see?

I don't see it. Could you give a simple example?

> Maybe a different API where you specify the agreement ID and gives you all the calendar and "factsheet" (contacts and websites) information, no?

I don't see any big difference between having this information in IIAs API and having it in other API served for given agreement ID. Signature and hash correspond only to cooperation conditions. Other data may change freely.

Currently the factsheet PDF is in Institutions API. Maybe we should keep iia-specific information in IIAs API and hei-specific information in Institutions API?

These questions remain unanswered:

> Is PDF factsheet not sufficient? Should we add an API for the information in factsheet? Do clients need this information in structural form? Do heis keep such information in the database?

**Comment by janinamincer-daszkiewicz** [comment]
A small clarification. Factsheet need not be in PDF format, URL is exchanged.
In my opinion all the extra organizational data should be part of the factsheet.

**Comment by MartaJuzepczuk** [comment]
I have added `blended` and removed average duration (https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/newTemplate). Not merged to the main branch yet. Unfortunately removing average is not backward compatible, so we will need to bump the API version to 3.0.0.

> “Contact” & “signing contact” is optional in API, “contact” is required in IIAM

Which contact should be mandatory in the API now? In the API we have:
* signing-contact (one, optional, on the IIA level)
* contact (many, optional, on the IIA level)
* receiving-contact (many, optional, on the mobility specification level)
* sending-contact (many, optional, on the mobility specification level).

The `contact` element's description starts with "A list of *other* partner contacts", "other" means probably "other than signing contact" (in the specification this field is directly after signing contact). So it would be strange if we make `contact` mandatory and leave `signing-contact` optional.

To make other changes I need your response.

**Comment by fmapeixoto** [comment]
My personal view of the IIA template is that is divided in 3 major parts:

1st part is the institution details
- Name
- OUnit
- Erasmus Code
- Contact Details (email, phone)
- General Website URL
- Faculty Website URL
- Course Catalogue Website URL

2nd part is the “Factsheet details”
- Incoming Student Nominations
- - Autumn Term
- - Spring Term
- Applications for incoming students
- - Autumn Term
- - Spring Term
- Application procedure for incoming students
- - Contact details (email, phone)
- - Website for Information
- Additional Requirements (multiple and each with following details)
- - Requirement
- - Details
- - Website for information (if applicable)
- Decision weeks limit (no longer than 5)
- Inclusion and Accessibility (multiple and with type infrastructure or service, and with the following fields each)
- - Available infrastructure or service
- - Description of the above
- - Contact details (email, phone)
- - Website for information
- Housing
- - Contact details (email, phone)
- - Website for information
- Visa
- - Contact details (email, phone)
- - Website for information
- Insurance
- - Contact details (email, phone)
- - Website for information
- Additional Information
- - Information on
- - Contact details (email, phone)
- - Website for information
- ToR weeks to issue

3rd part with cooperation conditions
- These are the extensive cooperations and there is no need to detail here

Given this, I think our IIA should cover the 3rd part which are the details of the IIA, with some institutional details to match who is who.
The 1st part is obtained from the institution details page if needed.
The 2nd part, which is related to useful information, in my opinion is not related to the agreement, for example, I may have a website for information on Visa while creating the agreement but then this URL for information on Visa may change 6 months later and I would like the information on the agreement to be always up-to-date. This information doesn’t affect the agreement itself and if it is in a separate API will always be up-to-date.

@MartaJuzepczuk I can't speak for HEIs if they save it locally or not, maybe some do and maybe others not. I have just analysed the template and, if the fields are there, in the Dashboard they are saved separately, as they may differ in information.

**Comment by janinamincer-daszkiewicz** [comment]
Francisco, thank you for your opinion. So it looks that we agree that institutional data should be left to institutional API, general info about the academic year etc. should be left to factsheets (which are already covered by other APIs). So we may concentrate on  the 3rd part.

Could anybody answer Marta's question concerning contacts?

**Comment by janinamincer-daszkiewicz** [comment]
We would really like to finalize the specification in March. Who can answer?

**Comment by mpuzar** [comment]
I am not an IIA expert, but... is it really so that contacts are now mandatory? I tried comparing the new call with the [old one](https://ec.europa.eu/programmes/erasmus-plus/resources/documents/erasmus-inter-institutional-agreement-pdf_en), and see no additional specification on that.

**Comment by MartaJuzepczuk** [comment]
@pleys, @fmapeixoto, can you confirm?

Moreover, according to the Francisco's post (https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/36#issuecomment-603275803) the contacts are not in the 3rd part which we want to serve in IIAs API.

**Comment by janinamincer-daszkiewicz** [comment]
Sorry, my mistake. I should reference your comment from https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/36#issuecomment-601656836.

**Comment by janinamincer-daszkiewicz** [comment]
> Moreover, according to the Francisco's post (#36 (comment)) the contacts are not in the 3rd part which we want to serve in IIAs API.

Does that mean that we do not need further decisions from Francisco?
Just approval of the draft version you have prepared?

**Comment by MartaJuzepczuk** [comment]
I'm not sure if my draft version is enough. We already have some contacts in IIAs API. Should we make them required or not? Keep them or move to another API? Should we make any changes in Instutions API? Should we also consider how we will exchange IIAs with the Dashboard now?

**Comment by kamil-olszewski-uw** [comment]
**University of Warsaw, International Relations Office**: Technically, all contact fields should be optional. But **signing-contact** should be required at the time of signing the agreement (and in the signed agreement, of course). Moreover, receiving and sending contacts (understood as coordinators at the level of faculties/institutes/etc.) should be required at the time of signing the agreement - preferably as **receiving-contact**s and **sending-contact**s at the mobility specification level (because it is very useful and convenient), but sending them as a **contacts** (in case a HEI has problems with fields not present in the IIA template) would also be acceptable.

**Comment by pleys** [comment]
> I am not an IIA expert, but... is it really so that contacts are now mandatory? I tried comparing the new call with the old one, and see no additional specification on that.

On the EC template it is mentioned that we should consider the IIAM as reference implementation and there contacts are required. Will we be able to exchange agreements with IIAM if we do not have contacts?

**Comment by pleys** [comment]
> I will add such field. Should it be added only to student mobilities for studies or to student mobilities for traineeships too? Should it be required? If so, what should be sent for old IIAs?

Sorry for my late answer but blended mobility is not connected to student mobilities for studies or traineeships, it is an additonal option.

**Comment by janinamincer-daszkiewicz** [comment]
> IIAM as reference implementation and there contacts are required

OK but *who* made the decision to make all these contacts required? EC? Francisco? Daiga? Reference implementation should be in accordance with the specification. What does the new template says in this respect?

**Comment by pleys** [comment]
> 2nd part is the “Factsheet details”

These is indeed fact sheet information that we need to make available. For now pdf's are used but the European Commission plans to make this kind of information available via the Erasmus+ App. I have no problem with updated this kind of information manually in the E+ Dashboard as for me it doesn't make sense to keep such data in my SIS database.

**Comment by janinamincer-daszkiewicz** [comment]
Does that mean that University of Gent will use the Dashboard for the agreements, not the local system? All of them, also cooperating conditions?

Why can not factsheets be used in the Erasmus App?  What added value is from having each field separately? On the list prepared by Francisco almost each position contains URL. My quess is that HEIS will put the same URL in all these positions. So why to have them separately?

I do not see the whole picture. In particular I still do not see how Erasmus App will get access to information abot the LAs which are edited in the local system. 

Of course we could design  *a separate* API for these factsheet details, for these HEIS which want to exchange this information which the partners. But making this part of the current IIA API would not help with the implementation. Also because factsheet data changes much more often then other details of the agreement.

I would like to know the opinion of SOP and MoveOn who have many clients.

**Comment by MartaJuzepczuk** [comment]
> Sorry for my late answer but blended mobility is not connected to student mobilities for studies or traineeships, it is an additonal option.

Look at the current iias response example https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v2/endpoints/get-response-example.xml. Where would you add this flag?

**Comment by pleys** [comment]
> Does that mean that University of Gent will use the Dashboard for the agreements, not the local system? All of them, also cooperating conditions?

For Ghent University I see it as follows [referring to the post](https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/36#issuecomment-603275803) from @fmapeixoto :
1st part is the institution details: we use API
2nd part is the “Factsheet details”: we update the Dashboard (manual update)
3rd part with cooperation conditions: we use the API

**Comment by janinamincer-daszkiewicz** [comment]
I see. Quite possible that more HEIs will choose such scenario. It means that we may need the API for factsheet details but *not* as part of the IIA API. Do you agree?

**Comment by fmapeixoto** [comment]
Yes, exactly, that's what I was trying to say from the beginning. Having a different API for this data not part of the IIA because this data can change at any time and it's not connected to any IIA in particular.

Regarding the contacts, in the IIAm we made it required to have at least one contact, in the beginning when choosing the partners because we need to send an email to the person so they know there's a new agreement there to be reviewed/signed.
This can be obtained from the Institution API or also I can adapt to check if the institution is in the EWP network and has the IIA API, as the agreement will be sent through the network, a contact is not required to be filled, what do you think?

**Comment by pleys** [comment]
> This can be obtained from the Institution API or also I can adapt to check if the institution is in the EWP network and has the IIA API, as the agreement will be sent through the network, a contact is not required to be filled, what do you think?

How would it work in the other way? Dashboard receives an IIA via the network?

**Comment by fmapeixoto** [comment]
Receiving an IIA without contacts? It should work because if we receive an IIA without contacts we will notify each person with permissions to access IIAs that there is a new IIA.

**Comment by fmapeixoto** [comment]
Is there actually situations that HEIs have no contacts at all or don't know what to put or actually don't know the contacts by the time of signing the agreement? I don't know, just wondering.

**Comment by pleys** [comment]
> Look at the current iias response example https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v2/endpoints/get-response-example.xml. Where would you add this flag?

I would add an additional container "!-- Blended mobilties. --" after "!-- Student mobility for traineeships. --". 

By the way, duration is still average in this example (should be total according to the new template)

**Comment by pleys** [comment]
> Is there actually situations that HEIs have no contacts at all or don't know what to put or actually don't know the contacts by the time of signing the agreement? I don't know, just wondering.

I guess in practice there will also be a contact but if it isn't required, it might go wrong.

**Comment by MartaJuzepczuk** [comment]
> I guess in practice there will also be a contact but if it isn't required, it might go wrong.

Why wrong? As I understood Francisco's argument (https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/36#issuecomment-606474146), they need contact to notify about a new agreement. In EWP network we don't need email notifications.

**Comment by MartaJuzepczuk** [comment]
> I would add an additional container "!-- Blended mobilties. --" after "!-- Student mobility for traineeships. --".

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/newTemplate/endpoints/get-response-example.xml

Is this what you mean?

> By the way, duration is still average in this example (should be total according to the new template)

Previously I sent you a link to the official IIAs API version, without my newest changes. Version with changes is here: https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/newTemplate, not released yet.

**Comment by pleys** [comment]
> https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/newTemplate/endpoints/get-response-example.xml

Is this what you mean?

Can you add the specification with the same grey as for student mobilities for studies (row 49) and student mobilities for traineeships (row 81) . And than the actual specification with true or false option. @fmapeixoto is blended mobility always applicable for the whole agreement in the IIAM or is it for specific academic year/partner... As far as I know for the whole agreement but we need to be sure

**Comment by MartaJuzepczuk** [comment]
This grey in rows 49 and 81 is the comment. I can add the comment to the example, but this is not so important now. I think that the answer to your question :

>  is blended mobility always applicable for the whole agreement in the IIAM or is it for specific academic year/partner

will be enough for me to add this in the right place.

**Comment by MartaJuzepczuk** [comment]
Useful links for today conversation:

- IIAs API, official version: https://github.com/erasmus-without-paper/ewp-specs-api-iias/
- IIAs API, version with my latest change: https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/newTemplate (blended: https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/181cd90253a642c89ac3d2dded06745a716dd315, remove average: https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/a7a29902f813fa15e3f220c62c33f95004369402)
- new API for factsheet (not complete yet): https://github.com/erasmus-without-paper/ewp-specs-api-factsheet
- Institutions API https://github.com/erasmus-without-paper/ewp-specs-api-institutions
- Agreement templates: https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/stable-v2/resources

**Comment by MartaJuzepczuk** [comment]
Which fact sheet data should we made mandatory in the new API? @fmapeixoto Which is required in the Dashboard?

**Comment by MartaJuzepczuk** [comment]
Should phone numbers and emails have maxOccurs="1" or unbounded?

Is it better to use our contact type for contact information (https://github.com/erasmus-without-paper/ewp-specs-types-contact/tree/v1.1.0) or have simple fields for email(s) and for phone(s)?

**Comment by fmapeixoto** [comment]
@MartaJuzepczuk in the Dashboard, at the moment, in the Default IIA Data page no field is required but I am not the right person to answer that question of what is required and how many times should occur because I don't understand much about mobilities and what should or should not be present.

**Comment by MartaJuzepczuk** [comment]
> @MartaJuzepczuk in the Dashboard, at the moment, in the Default IIA Data page no field is required

But some of them are required eg. if you decide to add an accessibility service or additional requirement (you can decide to add none of them, but if you add some, some of its attributes are required).

> but I am not the right person to answer that question of what is required and how many times should occur because I don't understand much about mobilities and what should or should not be present.

Anyway, thank you for the quick reply. Who can answer?

**Comment by daiga-kuzmane** [comment]
As things stand all values are mandatory since these are data points that are to be exposed towards mobile students.

**Comment by MartaJuzepczuk** [comment]
Ok. I will make everything mandatory, except fields explicitly marked as optional in the template.

**Comment by kamil-olszewski-uw** [comment]
As we have not received information that any of the topics in this issue are not resolved, we are closing the issue as announced.

**Comment by EvelienRenders** [comment]
Hi all,

It seems there is another field added to the template recently, the 'Field of Education - Clarification' text box
![image](https://user-images.githubusercontent.com/45844175/107149327-432d1a80-6958-11eb-9480-b5c645129707.png)

I found out about it here:
![image](https://user-images.githubusercontent.com/45844175/107149351-6bb51480-6958-11eb-9025-e9c1b9b59be2.png)
https://wiki.uni-foundation.eu/display/DASH/Upcoming+Functionalities

Do you know if that could be supported by the API as well? 
Somewhere in here I'm guessing..: https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/b5444d99250f15035560c32f60c56a0550bdc84a/endpoints/get-response-example.xml#L141

@MartaJuzepczuk

Best wishes from a snowy Holland,
Evelien

**Comment by kamil-olszewski-uw** [comment]
We know about this new field and about other changes resulting from the new IIA template. In a few days we will release a new version of the API which will include all these changes.

**Comment by EvelienRenders** [comment]
Great @kamil-olszewski-uw , thanks for the super quick response and the wonderful work you all are doing 🙏 
Know that it is greatly appreciated!

**Comment by EvelienRenders** [comment]
@kamil-olszewski-uw I don't know if this is the right place to ask, but it's connected to the discrepancy between Erasmus Dashboard & API's.

On the Erasmus Dashboard, de Academic Years (start & end) are chosen on the 'Contract level', while in the API they are exchanged under 'Cooperation Condition'-level. 
**In Dashboard:**
![image](https://user-images.githubusercontent.com/45844175/107213796-43d1b980-6a09-11eb-9709-b7268e6ffc4f.png)
**In API:**
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/f44b7951c8c326b490e8bf924e41adfcac7fc92f/endpoints/get-response-example.xml#L58

This means that if someone using the Dashboard initiates an agreement for 2021 > 2027, and the partner (using MobilityOnline / or whatever) changes one cooperation condition to 2021>2024, because for just a few ISCED codes they would like to have a shorter agreement. Then the Dashboard will interpret the change and split the IIA in two? One with the cooperation conditions for 2021>2027 and the other for 2021>2024. 

I'm unsure if the Dashboard supports this. Are there people from EUF on here? Perhaps @daiga-kuzmane?

**Comment by kamil-olszewski-uw** [comment]
@fmapeixoto - could you please tell us how it is done in the Dashboard and how it is translated when sending and receiving from EWP?

The idea in IIAs API is to set the total academic years of agreement by summing up the academic years of all cooperation conditions.

**Comment by RuudHaverlag** [comment]
> We know about this new field and about other changes resulting from the new IIA template. In a few days we will release a new version of the API which will include all these changes.

@kamil-olszewski-uw We are currently working to adapt OSIRIS (the SIS Evelien uses) for the new 2021-2027 IIA's. So I'm very interested in this new API! Is there a list of changes already available?

**Comment by kamil-olszewski-uw** [comment]
We have specified these changes at the business level, but these have not yet been translated into API structure changes.

**Comment by RuudHaverlag** [comment]
> We have specified these changes at the business level, but these have not yet been translated into API structure changes.
A list at business level would be very welcome already. Is that available somewhere? If not don't worry, in that case I'll wait a couple of days.

**Comment by kamil-olszewski-uw** [comment]
I'm afraid this is internal documentation for the working team. We kindly ask for a little more patience :-)

**Comment by EvelienRenders** [comment]
@kamil-olszewski-uw , just to check. The 6.0 version does not have this 'Field of education - Clarification' field like the Dashboard shows, right? (FYI @RuudHaverlag )
![image](https://user-images.githubusercontent.com/45844175/120310224-72381500-c2d6-11eb-929c-e25eadc60c05.png)

**Comment by kamil-olszewski-uw** [comment]
This field is present in the 6.0:

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/b8aed419061eba1b86c57389299841114bf500b1/endpoints/get-response.xsd#L490
