### ISSUE TITLE
Custom message to accompany proposal/change?

### ISSUE THREAD

**Issue by EvelienRenders** [erasmus-without-paper/ewp-specs-api-iias#37]
Hi all,

I'm unsure if this is the right place to ask this question, so please refer me to another spot if that is more relevant!

I'm wondering if a personal/custom message for the partner can be attached when submitting an IIA proposal/change. This is important for the 'human' connection and relationship that plays a part in negotiating an agreement. The alternative would be that the 'negotiation' is done via e-mail and only the signing is done via EWP.. but I'm under the impression that it would be more valuable if the whole process is supported. However, perhaps there are valid reasons why EWP should not be functioning as an 'instant messaging service' or replacing e-mails ;). 

Would love to hear your thoughts on this, or be referred to a previous discussion if this has already been discussed.

Thanks!
Evelien Renders (Radboud University, the Netherlands)

**Comment by EvelienRenders** [comment]
I now found this:

> **Let me remind you that the basic general assumption is that the discussion about the details is carried outside the EWP system.** To tell the truth, we still do not understand why the simplest approach, where after this discussion one of the partner sends the new version of the agreement and asks the other partner for approval, is not sufficient?
> 
> @BavoNootaert , @pleys , could you tell us where and why  exactly in your system this extra amendment is necessary?

_Originally posted by @janinamincer-daszkiewicz in https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/31#issuecomment-528750002_

**Comment by EvelienRenders** [comment]
@janinamincer-daszkiewicz , perhaps you know if a custom message/note is within scope right now?

**Comment by janinamincer-daszkiewicz** [comment]
I don't see such a field, have a look yourself:
- https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v2.2.2/endpoints/get-response.xsd
- https://github.com/erasmus-without-paper/ewp-specs-api-iias-approval/blob/v0.2.0/response.xsd

**Comment by EvelienRenders** [comment]
I discussed this with Paul Leys. Conclusion:
Negotiating should take place outside the EWP-sphere. Once the cooperation conditions are set, one partner can add the agreement and the other can accept. We do not want EWP to be used for ping-ponging agreements ;). 

I'll make sure my colleagues know :)
