### ISSUE TITLE
ISCED code / Subject area code of the IIA

### ISSUE THREAD

**Issue by StefanJahnke** [erasmus-without-paper/ewp-specs-api-iias#4]
During the technical workshop in Warsaw we were asking ourselves why the subject area code wasn't obligatory in the IIA template of the European Commission. Our colleagues now came back to us and informed us that the reason is that the agreements were published at the moment where there was a transition between the different ISCED systems (as discussed during the workshop as well).

The EC is open to make the field obligatory and that the EWP could make recommendations in that directions if deemed necessary. 

I personally don't see a need for having those codes a a necessary field. We of course need to include them as a possible data set (currently already part of WP3's data model). In the guidelines for implementation we can point out that we encourage institutions to include this field as it will greatly help the understanding of what students can be sent between different departments/faculties.

What do the others think? I am especially interested in the opinion of the practitioners  @pleys

**Comment by paulleys** [comment]
I agree not making it obligatory. Some agreements are institutional and I think ISCED is not relevant there. Especially when we want to broaden our scope in the future to non-Erasmus countries.

**Comment by StefanJahnke** [comment]
That should settle that then
