### ISSUE TITLE
ISCED and EQF definition

### ISSUE THREAD

**Issue by fmapeixoto** [erasmus-without-paper/ewp-specs-api-iias#42]
I am opening a new issue just to be recorded here in the processes.

I noticed during the full integration of the Dashboard with the EWP network that the two fields below do not match entirely.

1st. ISCED-F-Codes which in the EWP is defined to exist only 1 maximum or none and we allow multiple selection of isced-f-codes.

2nd. EQF-Level which in the EWP is defined to exist at least one to an unlimited number and in the template says it can be optional.

Is it possible to make these changes in the definition?

**Comment by MartaJuzepczuk** [comment]
The first issue has already been reported in #26.

**Comment by MartaJuzepczuk** [comment]
> 1st. ISCED-F-Codes which in the EWP is defined to exist only 1 maximum or none and we allow multiple selection of isced-f-codes.

We will allow many.

> 2nd. EQF-Level which in the EWP is defined to exist at least one to an unlimited number and in the template says it can be optional.

In EWP API specification we have separate type for student mobilities for studies and eqf level is present (and required) only for this type. For staff and traineeships there is no eqf level. Are you sure that we should allow cooperation conditions for student mobilities for studies without eqf level?

**Comment by MartaJuzepczuk** [comment]
> > 2nd. EQF-Level which in the EWP is defined to exist at least one to an unlimited number and in the template says it can be optional.
> 
> In EWP API specification we have separate type for student mobilities for studies and eqf level is present (and required) only for this type. For staff and traineeships there is no eqf level. Are you sure that we should allow cooperation conditions for student mobilities for studies without eqf level?

@fmapeixoto Could you answer? If we should change it, I would like to release this together with  multiple ISCED codes.

**Comment by fmapeixoto** [comment]
Sorry Marta, I spoke with Daiga about this and she told me that the official template indeed marks it as optional so should not be a required field.

Then maybe when receiving each institution may require or not if it is required for the cooperation.

**Comment by janinamincer-daszkiewicz** [comment]
Sorry, but I do think that this is not a good idea to allow *not to deliver* EQF for studies. From the practical point of view this atribute is *a must* for studies. I understand that the template puts this atttibute  in the same field for studies, staff and traineeships and *only* because of that makes the field optional.
Daiga, could you please talk to the commission and confirm with them that they *intentionally* allow to skip EQF for studies?

**Comment by daiga-kuzmane** [comment]
Skipping EQF would mean that instead of indicating separate EQF levels - the HEI accepts/offers them all. 
Does that help?

**Comment by fmapeixoto** [comment]
So either we keep it optional and the server who receives knows it's for them all or we make it required for the client to send anything (all in this case).

**Comment by kamil-olszewski-uw** [comment]
Only three EQF levels are used here. I think it would be better to send all three levels, which would be different from the situation when the level is missing or not yet determined.

**Comment by janinamincer-daszkiewicz** [comment]
@fmapeixoto, @daiga-kuzmane what is the final decision? We want to make the change in the specification in the coming days. I think that the proposal of @kamil-olszewski-uw is a good one - it is better to be more specific.

**Comment by fmapeixoto** [comment]
@janinamincer-daszkiewicz I don't see any problem with @kamil-olszewski-uw proposal. For me it's fine to have it that way.

**Comment by MartaJuzepczuk** [comment]
Many ISCED codes added in https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/c22b7917774a265aed3acd40891d0a4771a338c0

**Comment by janinamincer-daszkiewicz** [comment]
Problem with many ISCED codes has been solved. EQF levels will stay as they are.
