### ISSUE TITLE
Reference Link for Language Codes

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-iias#44]
Hi,

In the XSD page below, it is given a reference link to the CEFR definitions. 

Is there a similar reference link (ISO standard codes or similar?) for language codes to be used in IIA API?

We think including such data definition reference links would be good for knowing which standards to use.

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/f44b7951c8c326b490e8bf924e41adfcac7fc92f/endpoints/get-response.xsd#L450

Thanks,

**Comment by wrygiel** [comment]
This field makes use of [`xs:language` type](https://www.w3.org/TR/xmlschema11-2/#language).
