### ISSUE TITLE
Validation of get-response-example.xml in v4.0.0

### ISSUE THREAD

**Issue by SimonNesvera** [erasmus-without-paper/ewp-specs-api-iias#46]
[XML Schema Validator](https://dev-registry.erasmuswithoutpaper.eu/schemaValidator) seems to stop working on [get response example](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v4.0.0/endpoints/get-response-example.xml) in version 4.0.0:

`(#1) cvc-elt.1.a: Cannot find the declaration of element 'iias-get-response'.`

**Comment by wrygiel** [comment]
Might be worth to run [`update_schemas.py`](https://github.com/erasmus-without-paper/ewp-registry-service/blob/fc3e29239703b51d98ac921889543a7d1b3145d0/update_schemas/update_schemas.py) script, and update [the copy](https://github.com/erasmus-without-paper/ewp-registry-service/blob/fc3e29239703b51d98ac921889543a7d1b3145d0/src/test/resources/test-files/latest-examples/ewp-specs-api-iias-endpoints-get-response-example.xml) which is being validated by Registry's unit tests.

**Comment by SimonNesvera** [comment]
The bug seems to be fixed. Thanks.
