### ISSUE TITLE
Documentation on conditions-hash calculation is not clear

### ISSUE THREAD

**Issue by frangarcj** [erasmus-without-paper/ewp-specs-api-iias#53]
The only documentation about how to calculate the conditions-hash is the following:

```xml
          The SHA-256 digest of the cooperation-conditions element but *excluding*
          `sending-contact` and `receiving-contact` subelements. Before
          calculating the hash, the cooperation-conditions element should be normalized
          using Exclusive XML Canonicalization.
```

Should the element be formatted? Should we ignore whitespaces in element content (like carriage returns)?

In my humble opinion, a **get response example** followed by the **actual string that needs the SHA-256** is needed in order to clarify and test implementations.

At my university, we are struggling when integrating with several implementations from different vendors (QS, SOP, Erasmus Dashboard...) and having a reference test example would help a lot.

**Comment by umesh-qs** [comment]
@frangarcj 
I think this was already sorted under https://github.com/erasmus-without-paper/ewp-specs-api-iias/issues/48#issuecomment-813990007. What is the confusion now?

**Comment by frangarcj** [comment]
It's not a matter of sorted or not. I think the documentation is not clear for someone who just enters the EWP world. He/She doesn't need to start reading issues but just read the docs.

PD: @umesh-qs I think you are part of QS. can we contact through mail or something to talk about a specific case?

**Comment by BavoNootaert** [comment]
> Should the element be formatted? Should we ignore whitespaces in element content (like carriage returns)?

Could this be clarified? Currently, we verify the hash based on the document as received from the partner. But some partners compute the hash without whitespace, then format the xml (adding whitespace) before sending it in the response.

**Comment by umesh-qs** [comment]
Better to remove the formatting and convert it to a single-line string, by removing the new lines, tabs etc. We faced this issue with other service providers and came to an agreement on not using the formatting.

**Comment by mkurzydlowski** [comment]
> Some partners compute the hash without whitespace, then format the xml (adding whitespace) before sending it in the response.

This doesn't seem to be compliant with the documentation but you are right that it might be explicitly stated that using Exclusive XML Canonicalization means that the object being hashed must correspond to the response being sent and it shouldn't be altered after the hash is calculated.

**Comment by BavoNootaert** [comment]
OK. We will however relax our implementation: if the hash verification fails, we will try again on the xml with whitespace removed. That shouldn't be a problem.
