### ISSUE TITLE
Inconsistency between get-response XSD and example in StudentMobilitySpecification.eqf-level

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-specs-api-iias#54]
The [XSD](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/get-response.xsd#L535-L544) states:

`minOccurs="0" maxOccurs="unbounded"`

[Example](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/get-response-example.xml#L78-L80) states:

`At least one eqf-level is required for "mobility for studies".`

**Comment by mkurzydlowski** [comment]
Resolved in https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/55aa7276dbc54a01397cfa3040f053d5c5d926b4.

Thanks for noticing!
