### ISSUE TITLE
Multiple ISCED Codes in cooperation conditions? Verification needed.

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-iias#60]
Hi,

We need verification for the following issue from the maintainers.

REF: https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/48437c53937b7cef2e3f71872b7cddfa90f7566e/endpoints/get-response.xsd#L475

On the REF link, it says maxOccurs =1 for the isced code.
`<xs:element name="isced-f-code" type="xs:string" minOccurs="1" maxOccurs="1">
`
And it as it says for the subject area maxOccurs=unbounded and the isced code is inside this tag.
`<xs:element name="subject-area" type="SubjectArea" minOccurs="0" maxOccurs="unbounded">`

If this is the case, the following code is possible?  
I mean you can have only one "isced-f-code" inside a "subject-area". 
But you can have the subject-area section many times for different isced codes under one mobility condition spec?

```
<staff-teacher-mobility-spec>
     <mobilities-per-year>2</mobilities-per-year>
     <total-days-per-year>8</total-days-per-year>
     ...
     <subject-area>
         <isced-f-code>0314</isced-f-code>
     </subject-area>
     <subject-area>
         <isced-f-code>0425</isced-f-code>
     </subject-area>
     <subject-area>
         <isced-f-code>0922</isced-f-code>
     </subject-area>
</staff-teacher-mobility-spec>

```

**Comment by janinamincer-daszkiewicz** [comment]
Yes, you are right and your example is correct.

**Comment by sascoms** [comment]
Thank you for the confirmation, Janina.
