### ISSUE TITLE
EQF Levels - Not Required?

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-iias#61]
Hi,

REF: https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/48437c53937b7cef2e3f71872b7cddfa90f7566e/endpoints/get-response.xsd#L535

In the reference above, it is stated that minOccurs=0
That means it is not required to send this information in iia-get responses.

However, the explanation says that

> (If a particular student's level is not listed here, then this student should not be able to apply for this mobility.)

This seems to conflict with the not required state of the EQF info. 

If I did not misunderstand this, then how will it be possible to restrict students to use this iia in their applications when no EQF information exists in the IIA?

Could anybody please comment on this and clarify the explanation? 

Is there an ambiquity or do we misunderstand the explanation?

And how the EQF level/s should be interpreted if they do not exist in the IIA get content?

Thanks,

**Comment by kamil-olszewski-uw** [comment]
This should be understood as follows: If at least one EQF level is provided here and particular student's level is not listed here, then this student should not be able to apply for this mobility. We will consider correcting this comment.

**Comment by sascoms** [comment]
Thanks for the response @kamil-olszewski-uw 

To clarify it a bit more, the next question is what shall happen if the EQF level info is empty?

Shall we interpret this as "this IIA is open to all EQF levels"?

**Comment by kamil-olszewski-uw** [comment]
Exactly :-)

**Comment by kamil-olszewski-uw** [comment]
However, it would really be best to provide a list with all EQF levels so that the other party does not have to wonder if the missing EQF levels are due to a mistake or a draft of the IIA proposal.

**Comment by sascoms** [comment]
> However, it would really be best to provide a list with all EQF levels so that the other party does not have to wonder if the missing EQF levels are due to a mistake or a draft of the IIA proposal.

I agree on this. And therefore, we would like the minOccurs become 1 in the following spec:

` <xs:element name="eqf-level" type="ewp:EqfLevel" minOccurs="0" maxOccurs="unbounded"> 
`
to
` <xs:element name="eqf-level" type="ewp:EqfLevel" minOccurs="1" maxOccurs="unbounded"> 
`

**Comment by sascoms** [comment]
As a more general comment and idea:

I understand this type of flexibilities were good in the first years of the EWP.

However, it is now already a standard and every HEI and provider has to be inside.

Therefore I think we need stricter content rules/specs where there is no door left open for interpretation.

In my opinion, such flexibilities do not ease the the developers' job. On the contrary, it requires much more time to handle every flexibility and variation, unfortunately.

**Comment by Belenchusky** [comment]
I fully agree with @sascoms

**Comment by kamil-olszewski-uw** [comment]
The decision was made that this element would not be mandatory as it is optional in official IIA template.
