### ISSUE TITLE
Example iia conditions-hashes

### ISSUE THREAD

**Issue by tsiakmaki** [erasmus-without-paper/ewp-specs-api-iias#63]
Does the iia conditions-hashes values presented in the examples across the IIAs spec correspond to the ones that are actually expected? 
Because I could not reproduce the 
https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/example-scenario/01-A-get-response.part.xml#L31
for the specific cooperation-conditions.

**Comment by kamil-olszewski-uw** [comment]
No, these hashes are made up. We plan to make them correct one day, but the method of calculating the hash has been subject to corrections in recent months. Once we're sure this case is closed, we'll fix the hashes.
