### ISSUE TITLE
Signing contact

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iias#69]
The specification assumes that the signing contact is always the insitututional coordinator but at some institutions it may be the rector, dean or vice-dean or someone else who signs the IIA. Therefore I suggest to change the description of the signing-contact element accordingly.

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/cdecc5eae6233335646d13efae158e3a22cf4ce9/endpoints/get-response.xsd#L134

I assume in these cases, when for example dean is listed as signing contact, then the institutional coordinator should additionally be listed as a "common" contact, right?

**Comment by kamil-olszewski-uw** [comment]
> The specification assumes that the signing contact is always the insitututional coordinator but at some institutions it may be the rector, dean or vice-dean or someone else who signs the IIA. Therefore I suggest to change the description of the signing-contact element accordingly.

Ok, I'll make a request for such change.

> I assume in these cases, when for example dean is listed as signing contact, then the institutional coordinator should additionally be listed as a "common" contact, right?

I think so.
