### ISSUE TITLE
Add a signing date

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-iias#7]
Perhaps we should add a signing date to the IIA (the date at which the IIA has been signed by all parties)? Is this information stored by most of the partners? @erasmus-without-paper/all-members

**Comment by paulleys** [comment]
at Ghent University we do have this date (one field for Ghent, one for the partner). However if we add it, I should make it optional.

**Comment by georgschermann** [comment]
we also store this information for all participating HEIs

**Comment by wrygiel** [comment]
> at Ghent University we do have this date (one field for Ghent, one for the partner)

Good to know. In Poland, for example, I believe that we have only one date (not many).

**Comment by kaiqu** [comment]
>> at Ghent University we do have this date (one field for Ghent, one for the partner).
> 
> we also store this information for all participating HEIs

So - in the general case with multilateral IIAs, some of the Partners could potentially store (and transfer?) signing dates for _all_ Partners?

**Comment by georgschermann** [comment]
Depends on how or customers use these fields or not.
In most cases we would be able to supply these dates.

**Comment by wrygiel** [comment]
I believe that our API should then allow them to be supplied per each IIA partner.

**Comment by kaiqu** [comment]
> I believe that our API should then allow them to be supplied per each IIA partner

I assume you mean that the model/format should only support each Partner supplying _its own_ signing date, not also _its own version of the other Partners'_ signing dates (which Ghent seems to do)?

**Comment by wrygiel** [comment]
I meant the latter statement (which Ghent does).

But I'm not sure... Perhaps you are right, and it's more reasonable to expose only one's own signing date. @georgschermann what do you think?

**Comment by georgschermann** [comment]
since the agreement is most likely created and signed outside the reach of EWP under the lead of one HEI, it would make sense to allow one party to provide signature dates for all participants.
I think when signature dates are provided, the dates of all participants should be provided, it seems a little bit flawed to provide an agreement with all information except the signature date of the other participants.
