### ISSUE TITLE
Looking for test partners

### ISSUE THREAD

**Issue by serkanUH** [erasmus-without-paper/ewp-specs-api-iias#73]
Hi 

For the [technical admission](https://wiki.uni-foundation.eu/display/EWP/Joining+via+inhouse+mobility+software) to production registry I read 

> 3. The applicant institution performs testing with three partner institutions. 

Can we use this thread for finding test partners ? 

At Hasselt University we are planning to test IIA's and IIA Approvals mid January 2022. 
Feel free to contact us by reacting to this thread or via our mail you'll find in our [dev-manifest](https://staging-ewp.uhasselt.be/manifest.xml) if you are in need for testing as well.

(Sorry if this ain't the wright place for launching this , I couldn't find any other forum. Maybe we should start a discord or something to create a cummunity ;-) ).

Kind regards
Serkan

**Comment by janinamincer-daszkiewicz** [comment]
Sure, you can :)

**Comment by sascoms** [comment]
@serkanUH  
You can send an IIA to us if you would like
HEI ID: demo.erasmusport.com

**Comment by ghost** [comment]
@serkanUH We are joining the testing party like @sascoms
Our hei id is "kion.com.tr"
If there any provider or Inhouse developers want to test IIA, LA or the Nomination process, they can test with Kion. 
@janinamincer-daszkiewicz what do you think about of @serkanUH's suggestion about creating a discord community?

**Comment by janinamincer-daszkiewicz** [comment]
I do not use Discord myself, so have no opinion. I use Slack with my team (in MUCI). Do you think it would make sense to create something more 'official'? Once I asked at the Infrastructure Forum if we would like to have redmine for the group of EWP providers but reaction was negative.
Anyway, if I can be of help, let me know.
