### ISSUE TITLE
Workflow clarification

### ISSUE THREAD

**Issue by madiken21** [erasmus-without-paper/ewp-specs-api-iias#76]
After reading https://github.com/erasmus-without-paper/ewp-specs-mobility-flowcharts and most of opened and closes issues in this github, I still don't clearly understand IIA workflow. Could someone clarify some points to me ?

It is said that each partner has his own copy of IIA.

1) Do both copies has to be exactly the same ?

OR 

2) A's copy contains cooperatons conditions from B (sending) TO A (receiving), and B's copy contains cooperatons conditions from A TO B ?

In case 1) :
- Should cooperation condition hashes be the same on both IIAs ? If no, what does ensure that both IIAs have the same content ?
- Do both partners fill IIA on their own and then compare the 2 versions ? Or does one partner fill the IIA in place of other partner (after negotiating outside EWP) ?
- How Partner A filling his own IIA knows how to fill cooperation condition and receiving contact informations from Partner B ?

In case 2) :
- Should both IIAs copies be merged into a single one ?

What the purpose of PDF content inside get-response ?

**Comment by kamil-olszewski-uw** [comment]
> Do both copies has to be exactly the same ?

Yes.

However, both copies may contain minor differences. For example, the system of one university may support multiple ISCED codes for cooperation conditions, and the system of another university - only one ISCED code for each cooperation conditions. If both universities agree to such differences and there is no fear that they will lead to misunderstandings, they are acceptable. But in general, these should be exceptional situations and it would be best to avoid them.

> Should cooperation condition hashes be the same on both IIAs ? If no, what does ensure that both IIAs have the same content ?

No.

EWP API does not support automatic comparison of both copies of IIA. Users have to compare them on their own.

> Do both partners fill IIA on their own and then compare the 2 versions ? Or does one partner fill the IIA in place of other partner (after negotiating outside EWP) ?

It's up to partners how they want to get things done. But a common scenario is that they first settle the details outside of the EWP, and then one of the partners first introduces IIA into their system.

> How Partner A filling his own IIA knows how to fill cooperation condition and receiving contact informations from Partner B

Partner A does not have to complete all IIA data immediately. Partner B can download IIA from partner A and supplement its copy with e.g. the data of its coordinators or introduce changes and corrections to the data that partner A has already provided. Then partner A download IIA from partner B.

> What the purpose of PDF content inside get-response ?

This is an optional feature: sending IIA in human readable form. If your system is not going to generate or download these PDFs, you don't need to worry about them.
