### ISSUE TITLE
Maximum number of places per eqf-level

### ISSUE THREAD

**Issue by hwManSop** [erasmus-without-paper/ewp-specs-api-iias#77]
Is there a possibility to define conditions so that a university can define that they have 6 spots in total (for either bachelor or master) but for master there can be 2 at most
so valid constellations would be 
6 bachelor, 0 master
5 bachelor, 1 master
4 bachelor, 2 master

since there is only one field to define the amount of people that can be sent (mobilities-per-year) and no field for eqf levels to define the amount of people this decreased possibilities for universities for how they define their available places.

Is anyone else having this issue?

**Comment by kamil-olszewski-uw** [comment]
This was never considered as it was not specified in the official Interinstitutional Agreements template.
