### ISSUE TITLE
partner_hei_id parameter will become obsolete after unique client certificate change in manifest API. 

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-iias#80]
Once the new manifest changes are implemented index API can only be used to get list for only one HEI at a time.
This could have come handy to do a bulk refresh of the related IIAs periodically to make sure that any CNR failures are covered.

**Comment by umesh-qs** [comment]
Not only the IIA API, all APIs having index support will face the same problem

**Comment by mkurzydlowski** [comment]
You are right. 1-1 communication doesn't cover requesting data of multiple HEIs in one request. We believe that such communication should be split into multiple requests. This shouldn't be less efficient in fact. You can also check the slides from the last meeting.

**Comment by janinamincer-daszkiewicz** [comment]
Solved: https://github.com/erasmus-without-paper/general-issues/issues/44
