### ISSUE TITLE
ISCED clarification

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iias#87]
Are server implementers supposed to put the official name of the ISCED code into the isced-clarification field?

For example 0421. Should they put "Law" or an empty string in case they don't want to specify this any further?

If the latter is true, can you add a sentence to the specification that they are not supposed to do so?

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/84cf84ce6c6322942cb697a95b1d64074d4dc863/endpoints/get-response.xsd#L501-L507

**Comment by kamil-olszewski-uw** [comment]
It should be empty string if more precise description is not needed. Putting official name of ISCED code would be redundant and potentially prone to inconsistencies.

We thought that "additional details" would be a sufficient description, especially since it reflects the column from the official template. But we may consider adding a note that official name should not be included here.

**Comment by jiripetrzelka** [comment]
I think a note in the specification would be useful.

@kkaraogl I have noticed that all new IIAs from Dashboard contain the ofiical ISCED name in the ISCED clarification field. Can you please comment if you plan to change this?

**Comment by jiripetrzelka** [comment]
I would like to close this issue because Dashboard is already handling this correctly but there remains the question of whether to add the note to the specification. 

@kamil-olszewski-uw Is there any specific input you need before you can decide whether to add the note to the specification or not?

**Comment by kkaraogl** [comment]
I would also agree with adding an indication to the specification, so that newcomers won't have the same misunderstanding.

**Comment by janinamincer-daszkiewicz** [comment]
Please suggest the note and the place.

**Comment by jiripetrzelka** [comment]
I would suggest to change the annotation of the isced-clarification field to: 

This field contains additional details regarding `isced-f-code` field. It should be an empty string if a more precise description is not needed. You must not put the official name of the ISCED in this field.

**Comment by janinamincer-daszkiewicz** [comment]
> This field contains additional details regarding isced-f-code field. It should be an empty string if a more precise description is not needed. You must not put the official name of the ISCED in this field.

@kamil-olszewski-uw if this sounds OK to you, please prepare a request for @mkurzydlowski

**Comment by spinho-uporto** [comment]
From 2023-07-16-ChangesInFamilyIIA .pdf file (Infrastructure Forum meeting 2023-07-19):
![image](https://github.com/erasmus-without-paper/ewp-specs-api-iias/assets/78921213/a5f7a31f-136a-444e-b162-69cd8d16313e)


Shouldn't this change be only for version 7?
Removing the description of the ISCED code from the isced-clarification field implies changing the hash. Will approved agreements have to be approved again?

**Comment by janinamincer-daszkiewicz** [comment]
You are right. But 6.3.0 has already been issued :( 
Anyway, in 6.3.0 we have 'should' and 'must' in small letters so more like an recommendation: https://github.com/erasmus-without-paper/ewp-specs-api-iias/commit/29be06a3ef1a001b127ce362e9d1403acd47ed27.
W 7.0.0 it is done properly, in capital letters. And it will also contain an extra information - not to change it for mutually approved IIAs, to avoid re-approval. This change is not worth re-approval and preparing proper XSLT for it may be difficult (and also does not seem to be worth the effort).

**Comment by janinamincer-daszkiewicz** [comment]
This is this extra information: https://github.com/erasmus-without-paper/ewp-specs-api-iias/pull/129/commits/394b3e9a083847c171da88026086ce6e372b1900
