### ISSUE TITLE
The "native speaker" language level is not included

### ISSUE THREAD

**Issue by tsiakmaki** [erasmus-without-paper/ewp-specs-api-iias#88]
Currently, the [spec for iias](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/endpoints/get-response.xsd#L444) does not include the "native speaker" language level for a language skill -- in [las](https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/endpoints/get-response.xsd#L181) the 'CefrLevel' type is used. 

Should we consider 'NS' as a valid value in iias as well?

**Comment by kamil-olszewski-uw** [comment]
No, there is no "native speaker" option in official IIA template. Moreover, I don't think that universities would like to host only native speakers and I haven't heard of such a case.

**Comment by umesh-qs** [comment]
@kamil-olszewski-uw where can we find the official IIA template regarding "native speaker"?

**Comment by kamil-olszewski-uw** [comment]
There is "Recommended language skills" in official template: https://erasmus-plus.ec.europa.eu/sites/default/files/2021-09/digital_bilateral_agreement_intra-european_mobility.pdf

This section contains link to definitions of CEFR language levels: https://europa.eu/europass/en/common-european-framework-reference-language-skills - there is no "native speaker" option.

NS is not a part of CEFR, but often is used as addition to CEFR levels indicated mobilities, LAs etc.

**Comment by umesh-qs** [comment]
Thanks Kamil. And what is the reason NS is part of omobility API?

**Comment by kamil-olszewski-uw** [comment]
Native speaker is one of the language level options in the official LA template.

In the case of mobilities, information that the student is a native speaker is also useful - it may mean that the student doesn't have to participate, for example, in language placement tests or Online Language Support.
